### ISSUE TITLE
Spawn error on login

### ISSUE THREAD

**Issue by zodern** [NodeOS/NodeOS#101]
When I try logging in with the correct username and password, the output of npm start ends with 
```
[   56.228781] EXT4-fs (sda): mounted filesystem without journal. Opts: errors=remount-ro
Error re-mounting / as read-only
[   57.708570] random: nonblocking pool is initialized
[   79.981081] EXT4-fs (sdb): couldn't mount as ext3 due to feature incompatibilities
[   80.490840] EXT4-fs (sdb): mounting ext2 file system using the ext4 subsystem
[   80.543651] EXT4-fs warning (device sdb): ext4_update_dynamic_rev:698: updating to rev 1 because of new feature flag, running e2fsck is recommended
[   80.601219] EXT4-fs (sdb): mounted filesystem without journal. Opts: 
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: bin/users-services
Welcome to NodeOS!: username:  nodeos
Welcome to NodeOS!: password:  
child_process.js:1147
    throw errnoException(err, 'spawn');
          ^
Error: spawn ENOMEM
    at exports._errnoException (util.js:742:11)
    at ChildProcess.spawn (child_process.js:1147:11)
    at exports.spawn (child_process.js:980:9)
    at /root/lib/node_modules/logon/index.js:138:3
    at /root/lib/node_modules/logon/node_modules/prompt/lib/prompt.js:316:32
    at /root/lib/node_modules/logon/node_modules/prompt/node_modules/utile/node_modules/async/lib/async.js:142:25
    at assembler (/root/lib/node_modules/logon/node_modules/prompt/lib/prompt.js:313:9)
    at /root/lib/node_modules/logon/node_modules/prompt/lib/prompt.js:322:32
    at /root/lib/node_modules/logon/node_modules/prompt/lib/prompt.js:597:5
    at Interface.onLine (/root/lib/node_modules/logon/node_modules/prompt/node_modules/read/lib/read.js:111:5)
Welcome to NodeOS!: username:
```
It seems the error is from logon not finding nsh.
Do you want to see all of the output?

**Comment by piranna** [comment]
The error is about running out or RAM and not able to create the ```nsh``` process. This happens specially when using a 64bits build and only 128MB, we need to fix this. How have you started NodeOS?

**Comment by zodern** [comment]
I am  using `npm start` from NodeOS.  I increased the ram from 100 to 200 in scripts/start and it works now.  Thank you.

**Comment by piranna** [comment]
QEmu default value is 128, but on 64 bits we are using 256.

**Comment by zodern** [comment]
I ran git diff and I had at some point reduced the ram to 100.  Oops.  Sorry for bothering you with this.
