### ISSUE TITLE
dhcp client 

### ISSUE THREAD

**Issue by Coretool** [NodeOS/NodeOS#163]
Referring to the [Beta Goals] (https://github.com/NodeOS/NodeOS/issues/146), we nodeOs shall get a dhcp client ;): Its should be possible to use [this library] (https://github.com/apaprocki/node-dhcpjs)!

**Comment by piranna** [comment]
Good eye ;-) In fact, that library it's currently on our scope, but it's not usable yet because libuv returns only the actives network interfaces while we need all of them, so it's just a question of time :-)

**Comment by lite20** [comment]
2016 now! Did we make any progress with this? :P

**Comment by piranna** [comment]
Nopes :-) AFAIK the needed changes on libuv (be able to get a list of all the network interfaces, not only the ones with an IP address) are not already merged, and when it will be done, it will be included in a high-edge version of Node.js. Taking in account that we are still forced to use Node.js 0.11.14, there will be a long time until this get to be implemented, if any... :-( Another option would be to write a compiled module that access directly to the same functions libuv does.

**Comment by lite20** [comment]
Once again checking if we've made any progress XD

**Comment by luii** [comment]
@piranna how do you define all network interfaces?
do you mean interfaces that are deactivated (like when you use `ip down <iface>`)?

**Comment by piranna** [comment]
> @piranna how do you define all network interfaces?
> do you mean interfaces that are deactivated (like when you use ip down <iface>)?

Yes, I want to have all the interfaces you get when you do `ifconfig -a`.

By the way, the support on `libuv` is still missing :-(

**Comment by luii** [comment]
yes i think we could use `node-ife` for this.
its a bit outdated, but i could rewrite a new wrapper for it

**Comment by piranna** [comment]
> yes i think we could use node-ife for this.
> its a bit outdated, but i could rewrite a new wrapper for it

Would be nice if you [port it to nan2](https://github.com/postwait/node-ife/issues/10). Are you sure it list all available interfaces, also down ones? I'm not sure if the `.list()` function does it or not...

**Comment by luii** [comment]
@piranna I've mostly ported it to `Nan`, but im not so experienced with c/c++. How do you convert a char to a v8::Local<v8::Value>?

**Comment by piranna** [comment]
Threat it like a string with length == 1.

**Comment by luii** [comment]
okay i've done it like this Nan::New(char) but no success

**Comment by piranna** [comment]
You could be able to get some actual code and copy it, for example node-canvas use nan2 and has a lot of strings management.

**Comment by luii** [comment]
@piranna honestly i dont get it, i mean why cant i convert a cha[64] which behaves almost like a string to a `<v8::Value>` with Nan::New or Nan::To? I could push the current changes to the `nan2-port` branch

**Comment by piranna** [comment]
Without seeing the actual code I can't be able to give you an advice, but it's feasable, just only needs to do some types conversions.

**Comment by luii** [comment]
@piranna https://github.com/luii/node-ife/tree/nan2-port here it is

**Comment by piranna** [comment]
What are the problematic lines?

**Comment by luii** [comment]
every line with a Nan::Get or Set

**Comment by piranna** [comment]
Can you give one? What errors do you get?

**Comment by luii** [comment]
../src/wrapper.cc:271:76: Error: No suitable function call for »New(const char [10])«
     v8::Local<v8::Value> vrip = Nan::Get(o, Nan::New<v8::Value>("remote_ip"));

**Comment by piranna** [comment]
Don't use `v8` namespace, just only `Nan` one. Take a look on the code of node-canvas.

**Comment by piranna** [comment]
I think this code can help you: https://github.com/jprichardson/node-kexec/commit/711bbb9f8e5bf2392e4791e065abe903df0e5ee0

**Comment by luii** [comment]
I've made progress with the node-ife module.
I've got it to run with the newest node.js (9.2.0) version and the N-API C++ layer
i know its still in experimental but it works so much better in terms of user experience than accessing v8 directly.

```bash
~/Dokumente/git/node-ife
❯ node
> let ife = require('./build/Release/IFEBinding').IFE
undefined
> (node:17942) Warning: N-API is an experimental feature and could change at any time.
> let a = new ife()
undefined
> a.list()
[ { name: 'enp10s0\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000',
    ip: '192.168.178.39',
    broadcast: '192.168.178.255',
    netmask: '255.255.255.0',
    mac: '00:00:00:00:00:00' },
  { name: 'docker0\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000',
    ip: '172.17.0.1',
    broadcast: '172.17.255.255',
    netmask: '255.255.0.0',
    mac: '00:00:00:00:00:00' },
  { name: 'enp10s0\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000',
    ip: 'fe80::7160:dd80:88af:cee5',
    prefixlen: 64,
    mac: '00:00:00:00:00:00' } ]
>
```

**Comment by piranna** [comment]
Good job! :-D Could you be able to remove the trailing null chars on the interfaces name? And create a pull-request to include your client on usersfs? Lately I'm really busy with several works to dedicate some time to NodeOS, but still I'm available to review pull-requests :-)

**Comment by luii** [comment]
That should be no problem if i came this far already 💃

**Comment by piranna** [comment]
As I always said, one step at a time ;-) Start with the clean-up of the names :-)

**Comment by luii** [comment]
The trailing characters are gone, just used `NAPI_AUTO_LENGTH` which automaticly strips these characters. @piranna could you assign me the issue?

**Comment by piranna** [comment]
> @piranna could you assign me the issue?

Done :-)

**Comment by luii** [comment]
Thanks that was really fast! I'll port the other functions to napi and then it should work

**Comment by piranna** [comment]
Cool! Keep us informed :-)

**Comment by luii** [comment]
I've committed all my work.
But somethings not quite right. It wont set the interface up or down, i dont know if im doing it wrong or the programm isnt working.
But i got gdb to work and examined the code, looked for the error and got this interface structure, i think its ok but every time i launch the addon it fails with this:

```bash
let success = a.up({ name: 'enp10s0', ip: '192.168.178.39', broadcast: '192.168.178.255', netmask: '255.255.255.0', network: '192.168.178.0' })
                ^

Error: IP alias exists
    at Object.<anonymous> (/home/philipp/Dokumente/git/node-ife/index.js:6:17)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

which basiclly means the interface is still up, which is true and then i turn it of and try it again and i get this: 

```bash
let success = a.up({ name: 'enp10s0', ip: '192.168.178.39', broadcast: '192.168.178.255', netmask: '255.255.255.0', network: '192.168.178.0' })
                ^

Error: ioctl error setting IP address
    at Object.<anonymous> (/home/philipp/Dokumente/git/node-ife/index.js:6:17)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

like i said above i dont know if its me and i make wrong inputs or something else
but the gdb dump says following:

```bash
277       if(areq->family == AF_INET) {
278         memcpy(ifr.ifr_name, realreq.ifname, IFNAMSIZ);
279         ((struct sockaddr_in *)&ifr.ifr_addr)->sin_addr.s_addr = areq->ipaddr.s_addr;
280         ((struct sockaddr_in *)&ifr.ifr_addr)->sin_family = AF_INET;
279         ((struct sockaddr_in *)&ifr.ifr_addr)->sin_addr.s_addr = areq->ipaddr.s_addr;
281         ((struct sockaddr_in *)&ifr.ifr_addr)->sin_port = 0;
282         
284           memcpy(ifq.ifr_name, realreq.ifname, IFNAMSIZ);
314         }
335     }
(gdb) p ifr
$1 = {ifr_ifrn = {ifrn_name = "enp10s0\000\000\000\000\000\000\000\000"}, ifr_ifru = {ifru_addr = {sa_family = 2, sa_data = "\000\000\300\250\262'\000\000\000\000\000\000\000"}, ifru_dstaddr = {sa_family = 2, 
      sa_data = "\000\000\300\250\262'\000\000\000\000\000\000\000"}, ifru_broadaddr = {sa_family = 2, sa_data = "\000\000\300\250\262'\000\000\000\000\000\000\000"}, ifru_netmask = {sa_family = 2, 
      sa_data = "\000\000\300\250\262'\000\000\000\000\000\000\000"}, ifru_hwaddr = {sa_family = 2, sa_data = "\000\000\300\250\262'\000\000\000\000\000\000\000"}, ifru_flags = 2, ifru_ivalue = 2, ifru_mtu = 2, ifru_map = {
      mem_start = 2860534255920873474, mem_end = 0, base_addr = 0, irq = 0 '\000', dma = 0 '\000', port = 0 '\000'}, ifru_slave = "\002\000\000\000\300\250\262'\000\000\000\000\000\000\000", 
    ifru_newname = "\002\000\000\000\300\250\262'\000\000\000\000\000\000\000", ifru_data = 0x27b2a8c000000002 <error: Cannot access memory at address 0x27b2a8c000000002>}}

IFE::up (env=0x2230430, info=0x7fffffffc590) at ../ife.cc:378
378           char *error = if_error();
380           napi_throw_error(env, nullptr, (const char*) error);
381           return nullptr;
391       }
```

these long strings like ifrn_name are \0 terminated with a size of IFNAMSIZ which is around 14-16 bytes if im correct its either 14 or 16 dont know.

@piranna do you have any clue of what went wrong?

**Comment by luii** [comment]
@piranna i've found the problem, it could not make a ioctl call because of a invalid File descriptor. It was never set and it was initialized with `-1` so it could not make a appropriate call. After i cleaned everything up i'll push it to my repo.
