### ISSUE TITLE
nsh crashes on empty pipe

### ISSUE THREAD

**Issue by Marak** [NodeOS/NodeOS#217]
Scenario: Entering an empty `|` operator crashes on latest docker image.

Run:

```bash
docker run -t -i nodeos/nodeos
```

Then once you get the nsh prompt, entering the following command yields the following error:

```bash

|

/root/lib/node_modules/bin-nsh/node_modules/lib-cmdparse/index.js:15
    if (env && item[0] != '-' && item.indexOf('=') > 0) {
                                      ^
TypeError: Object #<Object> has no method 'indexOf'
    at /root/lib/node_modules/bin-nsh/node_modules/lib-cmdparse/index.js:15:39
    at Array.forEach (native)
    at parse (/root/lib/node_modules/bin-nsh/node_modules/lib-cmdparse/index.js:13:9)
    at run (/root/lib/node_modules/bin-nsh/nsh.js:123:16)
    at readline (/root/lib/node_modules/bin-nsh/nsh.js:93:7)
    at /root/lib/node_modules/bin-nsh/nsh.js:176:5
    at Interface._onLine (readline.js:200:5)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
<---- first runner exited
<---- stopping init because BOOT=0 (set BOOT=1 to override)
```

**Comment by Coretool** [comment]
Can't you guys just stop writing '?' and co into that console ? That would make everything much easier ^^

**Comment by Marak** [comment]
What's up @Coretool?

I don't understand your response?

**Comment by piranna** [comment]
Docker images are outdated. Seems now Docker allow to use FUSE and mount
external filesystems if you enable some capabilities on the container. We
are volunteers that work on NodeOS on our free time so our resources are
very limited, any help on this area or any other and pull-requests are
greatly welcome.

**Comment by Marak** [comment]
I work on many open-source projects full-time. I understand your pain.

More specifically to docker related issues, I had to spend 30+ hours this year configuring the docker setup for my project: https://github.com/bigcompany/hook.io

We aren't using docker anywhere in production, I put the images together to help lower the entry barrier for other developers to hack on the project.

What is my point? I want to contribute to the NodeOS project, specifically in userland. Unfortunately, I don't have the bandwidth to deep dive into the stack here to make the Docker image work. More importantly, I'm not sure if I have the domain knowledge to actually accomplish the task in any reasonable amount of time.

So really, I am proposing a trade. If you can provide the time to make a quick and easy way to get a development instance of NodeOS working locally, I can provide the time to make contributions.

Regardless...this project is great work. I look forward to more upcoming releases.

**Comment by piranna** [comment]
> I work on many open-source projects full-time. I understand your pain.

Lucky you are :-) I try to get open-source friendly jobs too (Spain is too much prehistoric on this point due to we have plenty of "employersaurs" here... :-( ).


> What is my point? I want to contribute to the NodeOS project, specifically in userland. Unfortunately, I don't have the bandwidth to deep dive into the stack here to make the Docker image work. More importantly, I'm not sure if I have the domain knowledge to actually accomplish the task in any reasonable amount of time.

I'm not a Docker expert at all, and in fact I moved to [vagga](https://github.com/tailhook/vagga) since uses user containers that make them easier to use and more secure by not needing administrator permissions (you should really take it a look ;-) ) and `vagga` images are compatible with Docker. LXC containers support is somewhat outdated due to the point the don't support to mount filesystems for security reasons, but if Docker now start to allow it, maybe with your help we could re-enable support for them :-)


> So really, I am proposing a trade. If you can provide the time to make a quick and easy way to get a development instance of NodeOS working locally, I can provide the time to make contributions.

Fair trade :-) Until that, you can use QEmu instance of Docker to test it locally. We need to lightweight the build process so we could be able to re-enable prebuild images (CI server fails at random points due to so how much CPU heavy is the build process...) but you could be able to generate them yourself in some simple steps from the README.md. If you give it a try, I'll try to find some time to take a look to the current status of Docker, try to re-enable its support and upload new images to Docker Hub ;-)


> Regardless...this project is great work. I look forward to more upcoming releases.

Thank you for your compliments! :-D

**Comment by Marak** [comment]
@piranna -

I will review the installation documentation tonight and attempt to build with QEmu instance.

Will let you know if / when I get stuck.

Cheers.

**Comment by piranna** [comment]
You are welcome :-) Keep us informed of your progress ;-)

**Comment by lite20** [comment]
> What is my point? I want to contribute to the NodeOS project, specifically in userland. Unfortunately, I don't have the bandwidth to deep dive into the stack here to make the Docker image work. More importantly, I'm not sure if I have the domain knowledge to actually accomplish the task in any reasonable amount of time.

I do have a bit of docker experience, and by a bit I mean I wrote an entire engine using it for the place I currently work. So if you need a hand, just pop me questions. I've been really busy lately looking over the build process trying to clean it up and slim it down while documenting as much as possible so I won't be able to carry the effort for you but I can definitely kick in where your bandwidth kicks out ;) @Marak

Welcome to the project by the way!

**Comment by luii** [comment]
This problem is still exists in the newer NodeOS build.
If you time `|` into nsh you get following error and you get logged out
![nodeos](https://cloud.githubusercontent.com/assets/8077014/14408852/61fbc064-ff05-11e5-898f-4f3751e1f2c0.png)

**Comment by piranna** [comment]
`nsh` has not yet been updated on NodeOS images, I have got [some cool progresses](https://github.com/piranna/nsh) but I'm stuck with a [Node.js bug](https://github.com/nodejs/node/issues/5574), help is greatly considered.

**Comment by lite20** [comment]
Has this been repaired yet?

**Comment by luii** [comment]
Since nsh hasnt been updatet, yes it still exists

**Comment by lite20** [comment]
okay I'll leave it open then.

**Comment by luii** [comment]
How is the Status of this issue @piranna

**Comment by piranna** [comment]
I haven't reviewed it, feel free to give it a try.
