### ISSUE TITLE
"Operation not permitted" on docker image

### ISSUE THREAD

**Issue by luii** [NodeOS/NodeOS#227]
Hey,

@piranna i managed to create a docker image by hand and got this error do think you can fix this or do you have a clue how to fix it?
The `nodeos-barebones` create a invalid tar file so i unpacked `barebones` and packed again with this command: `tar -cf barebones.tar bin/ dev/ lib/ sbin/ init | docker import - barebones`

```bash
[philipp@arch NodeOS]$ docker run -i 497fb770977e
mount: Operation not permitted
{ [Error: EPERM, Operation not permitted 'proc'] errno: 1, code: 'EPERM', path: 'proc', syscall: 'mount' }
fs.js:897
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: EEXIST: file already exists, symlink '/proc/mounts' -> '/etc/mtab'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at /lib/node_modules/nodeos-mount-filesystems/server.js:394:8
    at /lib/node_modules/nodeos-mount-filesystems/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:82:15)
termination: Operation not permitted
```

```bash
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              497fb770977e        7 minutes ago       54.75 MB
usersfs             latest              ce2793db7999        13 minutes ago      54.75 MB
rootfs              latest              5dbee56f5abb        13 minutes ago      19.77 MB
initramfs           latest              f209c1c10720        14 minutes ago      19.77 MB
barebones           latest              05c860e2d94c        23 minutes ago      17.06 MB
```

The one with the "none" in it is the nodeos image

**Comment by luii** [comment]
The build process on `barebones`, `ìnitramfs` and so on was quitly and gave me no error

**Comment by piranna** [comment]
> The nodeos-barebones create a invalid tar file so i unpacked barebones

I found [a bug on tar-stream](https://github.com/mafintosh/tar-stream/issues/44) regarding to this some time ago, but no advance yet.


> and packed again with this command: tar -cf barebones.tar bin/ dev/ lib/ sbin/ init | docker import - barebones

Good trick, maybe we can use it as a workaround until the bug gets fixed :-) Only problem would be related to files permissions... :-(


> Error: EEXIST: file already exists, symlink '/proc/mounts' -> '/etc/mtab'

This error is due to NodeOS initram trying to create a `/etc/mtab` entry, that on Docker it makes sense that's already there. That symlink is created at https://github.com/NodeOS/nodeos-mount-filesystems/blob/7937600616a6987d472d0e85d9c4143ec9585c97/server.js#L394, if you want to do a pull-request to swallow that exception (but no others) I would happily merge it :-) And the same applies to the tar file trick... :-D

**Comment by luii** [comment]
> This error is due to NodeOS initram trying to create a /etc/mtab entry, that on Docker it makes sense that's already there.

How do you mean this, does Docker creates a own `mtab` in the container?

**Comment by piranna** [comment]
>> This error is due to NodeOS initram trying to create a /etc/mtab entry,
that on Docker it makes sense that's already there.
>
> How do you mean this, does Docker creates a own mtab in the container?

Yes, I think Docker has its own /etc/mtab and when nodeos-mount-filesystems
try to create the symlink then you get that error. In that case I think the
one of nodeos-mount-filesystems should be ignored.

**Comment by luii** [comment]
@piranna i could rewrite it when there is a symlink to `mtab` on docker for example or on other virutal machines then it dont creates a symlink and just use `/proc/mounts` then i wouldnt need to swallow the exception

**Comment by piranna** [comment]
Yes that's the point, just swallow rhe exception if destination exists,
otherwise throw it.

**Comment by luii** [comment]
@piranna i edited the pull request

**Comment by piranna** [comment]
Added some comments :-)

**Comment by luii** [comment]
@piranna i was able to replicate the bug with the tar files.
I had 2 `.cpio` files, one containing just plain pictures and one generated with `cpio.txt` and `gen_init_cpio`.
I also copied `tar-stream` and `cpio-stream` into a test folder and added on both debug messages.
The first test: `cat archive.cpio | ./index.js > converted.tar`
And the second test (init.cpio is generated with gen_init_cpio): `cat init.cpio | ./index.js > barebones.tar`
Till this point everything went fine
but after i generated it and tryed to list all the files, the second test got a padded header like your issue on 

```bash
[philipp@arch test] $ tar -tvf barebones.tar
tar: substitute for empty member name "."
d--x--x--x 0/0               0 2016-04-16 19:18 
dr-xr-xr-x 0/0               0 2016-04-16 19:18 bin
d--------- 0/0               0 2016-04-16 19:18 dev
d--x--x--x 0/0               0 2016-04-16 19:18 lib
d--x------ 0/0               0 2016-04-16 19:18 sbin
---x------ 0/0            5416 2016-04-16 18:28 init
l--x------ 0/0              10 2016-04-16 19:18 sbin/init -> /bin/node
-r-xr-xr-x 0/0          653216 2016-04-02 21:31 lib/libc.so
lr-xr-xr-x 0/0               8 2016-04-16 19:18 lib/ld-musl-x86_64.so.1 -> libc.so

tar: Jump to the next header.
tar: A single zero block in 1466
tar: Complete with failure status due to previous errors
```

while the first test completly fine is
```bash
[philipp@arch test]$ tar -tvf converted.tar
-rw-r--r-- 1000/100    1544251 2016-04-16 16:27 doc/NodeOS.odp
drwxr-xr-x 1000/100          0 2016-04-16 16:27 doc
-rw-r--r-- 1000/100       9008 2016-04-16 16:27 doc/NodeOS layer 1.png
-rw-r--r-- 1000/100      14873 2016-04-16 16:27 doc/NodeOS layer 4.png
-rw-r--r-- 1000/100      11843 2016-04-16 16:27 doc/NodeOS layer 3.png
-rw-r--r-- 1000/100       2440 2016-04-16 16:27 doc/NodeOS.dia
-rw-r--r-- 1000/100      11177 2016-04-16 16:27 doc/NodeOS layer 2.png
```

I also tested it with the GNU tar and it went completly fine like the one above.
So my assumption is that either `cpio-stream` or `tar-stream` adds zeros onto the symliks and skips the rest, you can see this behavior if you add an `i` to the `tar -itvf converted.tar`.
If the stream adds zeros behind every symlink then its like a bad sector and it cant finds anything.

**Comment by piranna** [comment]
Awesome forensics work, thank you! :-D Yes, as I've put before seems to be a bug on `tar-stream`. Could you be able to confirm if there's the beginning of a zero block on 1466 byte, and if so remove it and test if you can list the files correctly? Tar format is a concatenation of 512 bytes blocks, so there should not be any problem by removing it. If so, then we can notify @mafintosh about this point, seems it would be easy to fix :-)

**Comment by piranna** [comment]
Oh, and also check if the block before the zero block is a symlink! :-P

**Comment by piranna** [comment]
[tar format is sh*t](http://www-01.ibm.com/support/docview.wss?uid=swg21270445)... Try to use the `-i` flag, seems GNU tar now expect two zero blocks to identify end of files... Someone could argue it's a bug on `tar-fs` by not adding them, but I honestly think it's a bug on Docker by not using standard compliant options.

**Comment by luii** [comment]
That would be possible too!

**Comment by piranna** [comment]
> That would be possible too!

Check it and give me your conclussions ;-)

**Comment by luii** [comment]
Well, i hexdumped the tar and got this https://gist.github.com/luii/6a7d3e1dece379358863fdb69135f817
I cut the most useless content like picture information.
And added a symlink with the name `layer1` pointing to `NodeOS Layer 1.png` and guess what i got the same error! I also added comments to clarify things on the gist!

**Comment by piranna** [comment]
> And added a symlink with the name layer1 pointing to NodeOS Layer 1.png and guess what i got the same error!

Yes, the error is related to symlinks :-P

I've reviewed the dump and definitely seems to be a problem with the zeroed blocks. Have you tried to use the `-i` flag as is dictated on the link I gave you before?

**Comment by piranna** [comment]
I've done a little clean-up of your dump at https://gist.github.com/piranna/c69669190da25374b6a810d4288a1809. Since the symlink don't have a zeroed block after it, and the missing entries are just the ones after the symlink, could it be the blocks containing the file info are being ignored? If so, it would be as easy as just add a zeroed block after the symlink... Knowing the offset where the symlink is defined in the tar file, it would be as simple as split the tar file and insert 512 zeroed bytes using `dd` command...

**Comment by luii** [comment]
Today i want to test if i repack the corrupted tar with GNU Tar if it then gives me a other result.

**Comment by piranna** [comment]
And later compare the results? Ok.

**Comment by luii** [comment]
Yeah thats the plan

**Comment by luii** [comment]
> Have you tried to use the -i flag as is dictated on the link I gave you before?
Dont works for me. :-(

Well on the gnu tar are more zeroed blocks at the end and the order the files are set inside the archive is different but the symlinks are all the same

**Comment by piranna** [comment]
I think the important part here is, does gbu tar add one (or more) zeroed
blocks after symlinks? I think this is the problem key.

**Comment by luii** [comment]
> It implementes USTAR with additional support for pax extended headers. It should be compatible
> with all popular tar distributions out there (gnutar, bsdtar etc)

It could also be that are the pax are causing this problem and docker dont recognize this.
But GNU tar recognizes the headers

Here the dump of one generated with GNU (left) and one generated through `cpio2tar` (right)

![hexdump](https://cloud.githubusercontent.com/assets/8077014/14588013/03b5f348-04bf-11e6-9268-d50739162398.png)

**Comment by piranna** [comment]
I don't think it's a problem of incorrect headers since vagga can use
cpio2tar files correctly, I think instead is a problem with some aditional
ckecks done by gnu tar, like the zeroed block after symlinks. Do you have
uploaded somewhere the generated tar files so I could be able to check them
too?
El 17/4/2016 17:11, "Philipp Czarnetzki" <notifications@github.com>
escribió:

It implementes USTAR with additional support for pax extended headers. It
should be compatible
with all popular tar distributions out there (gnutar, bsdtar etc)

It could also be that are the pax are causing this problem and docker dont
recognize this.
But GNU tar recognizes the headers

Here the dump of one generated with GNU (left) and one generated through
cpio2tar (right)

[image: hexdump]
<https://cloud.githubusercontent.com/assets/8077014/14588013/03b5f348-04bf-11e6-9268-d50739162398.png>

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/NodeOS/NodeOS/issues/227#issuecomment-211042545>

**Comment by luii** [comment]
Here you have it [test.tar.gz](https://github.com/NodeOS/NodeOS/files/222735/test.tar.gz)
- `init.cpio` was created through `gen_inti_cpio`
- `barebones.tar` was converted to tar with `cpio2tar` from `init.cpio`
- `cpio2tar.cpio` was created with `cpio -ov`
- `fromcpio.tar` was converted with `cpio2tar` from `cpio2tar.cpio`
- `gnu.tar` was repacked from `fromcpio.tar`

**Comment by piranna** [comment]
How did you repacked `gnu.tar`?

**Comment by luii** [comment]
i unpacked `fromcpio.tar` put all the files in a folder and repacked with tar -cf
mostly to check if any files were corrupted during the conversion of `cpio2tar`

**Comment by piranna** [comment]
> i unpacked fromcpio.tar put all the files in a folder and repacked with tar -cf
> mostly to check if any files were corrupted during the conversion of cpio2tar

That's cool :-) How did you do the extraction of `fromcpio.tar`? I think we have the problem here...

**Comment by luii** [comment]
with gnome's archive manager

**Comment by piranna** [comment]
> with gnome's archive manager

file-roller? It's showing me a pop-up with the same errors from command line gnu tar and later the window is not showing files...

**Comment by luii** [comment]
i have created a cpio using cpio like this: `cpio -o < docs/ > archive.cpio` then i converted it with `cat archive.cpio | ./index.js > converted.tar`

**Comment by piranna** [comment]
I think I've found it, and in fact, [it's not something new](http://bugs.python.org/issue1167128). Seems gnu `tar` (booooh...) requires the file size of the symlink entry header to be zero, while we are setting it to the length of the target path (22), and in fact it's the only notable difference between `fromcpio.tar` and `gnu.tar` files...

```
00003e00  64 6f 63 73 2f 6c 61 79  65 72 31 00 00 00 00 00  |docs/layer1.....|
00003e10  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00003e60  00 00 00 00 30 30 30 37  37 37 20 00 30 30 31 37  |....000777 .0017|
00003e70  35 30 20 00 30 30 30 31  34 34 20 00 30 30 30 30  |50 .000144 .0000|
00003e80  30 30 30 30 30 32 32 20  31 32 37 30 34 35 32 31  |0000022 12704521|
00003e90  33 36 31 20 30 31 34 33  37 37 20 00 32 4e 6f 64  |361 014377 .2Nod|
00003ea0  65 4f 53 20 6c 61 79 65  72 20 31 2e 70 6e 67 00  |eOS layer 1.png.|
00003eb0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00003f00  00 75 73 74 61 72 00 30  30 00 00 00 00 00 00 00  |.ustar.00.......|
00003f10  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00003f40  00 00 00 00 00 00 00 00  00 30 30 30 30 30 30 20  |.........000000 |
00003f50  00 30 30 30 30 30 30 20  00 00 00 00 00 00 00 00  |.000000 ........|
00003f60  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
```

```
00006600  64 6f 63 73 2f 6c 61 79  65 72 31 00 00 00 00 00  |docs/layer1.....|
00006610  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00006660  00 00 00 00 30 30 30 30  37 37 37 00 30 30 30 31  |....0000777.0001|
00006670  37 35 30 00 30 30 30 30  31 34 34 00 30 30 30 30  |750.0000144.0000|
00006680  30 30 30 30 30 30 30 00  31 32 37 30 34 35 32 31  |0000000.12704521|
00006690  33 36 31 00 30 31 35 35  36 33 00 20 32 4e 6f 64  |361.015563. 2Nod|
000066a0  65 4f 53 20 6c 61 79 65  72 20 31 2e 70 6e 67 00  |eOS layer 1.png.|
000066b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00006700  00 75 73 74 61 72 20 20  00 70 68 69 6c 69 70 70  |.ustar  .philipp|
00006710  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00006720  00 00 00 00 00 00 00 00  00 75 73 65 72 73 00 00  |.........users..|
00006730  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
```

Probably this is due to the fact `cpio2tar` is using stream API, since `cpio-stream` module send the symlink path as it's content. I'll notify to @mafintosh about this and put `cpio2tar` in an independent module so we can be able to test this easily.

**Comment by luii** [comment]
I saw the difference earlier but didnt thought that it could make such problems

**Comment by piranna** [comment]
It shouldn't, that's why I said it's a gnu tar bug.

**Comment by piranna** [comment]
I've fixed `tar-stream` and in a quick check seems [cpio2tar](https://github.com/piranna/cpio2tar) is now generating valid tar files regarding to symlinks size :-)

```
[piranna@Latitude:~/Proyectos/cpio2tar]
 (master) > find test/ | cpio -o -H newc > archive.cpio 
1 bloque

[piranna@Latitude:~/Proyectos/cpio2tar]
 (master) > hd archive.cpio 
00000000  30 37 30 37 30 31 30 30  34 31 43 30 43 41 30 30  |0707010041C0CA00|
00000010  30 30 34 31 46 44 30 30  30 30 30 33 45 38 30 30  |0041FD000003E800|
00000020  30 30 30 33 45 38 30 30  30 30 30 30 30 32 35 37  |0003E80000000257|
00000030  31 36 32 45 38 43 30 30  30 30 30 30 30 30 30 30  |162E8C0000000000|
00000040  30 30 30 30 30 38 30 30  30 30 30 30 30 33 30 30  |0000080000000300|
00000050  30 30 30 30 30 30 30 30  30 30 30 30 30 30 30 30  |0000000000000000|
00000060  30 30 30 30 30 36 30 30  30 30 30 30 30 30 74 65  |00000600000000te|
00000070  73 74 2f 00 30 37 30 37  30 31 30 30 34 30 42 34  |st/.0707010040B4|
00000080  45 32 30 30 30 30 38 31  42 34 30 30 30 30 30 33  |E2000081B4000003|
00000090  45 38 30 30 30 30 30 33  45 38 30 30 30 30 30 30  |E8000003E8000000|
000000a0  30 31 35 37 31 36 32 45  30 36 30 30 30 30 30 30  |0157162E06000000|
000000b0  30 37 30 30 30 30 30 30  30 38 30 30 30 30 30 30  |0700000008000000|
000000c0  30 33 30 30 30 30 30 30  30 30 30 30 30 30 30 30  |0300000000000000|
000000d0  30 30 30 30 30 30 30 30  30 45 30 30 30 30 30 30  |000000000E000000|
000000e0  30 30 74 65 73 74 2f 66  69 6c 65 2e 74 78 74 00  |00test/file.txt.|
000000f0  61 20 66 69 6c 65 0a 00  30 37 30 37 30 31 30 30  |a file..07070100|
00000100  34 30 42 34 44 44 30 30  30 30 41 31 46 46 30 30  |40B4DD0000A1FF00|
00000110  30 30 30 33 45 38 30 30  30 30 30 33 45 38 30 30  |0003E8000003E800|
00000120  30 30 30 30 30 31 35 37  31 36 32 45 38 37 30 30  |00000157162E8700|
00000130  30 30 30 30 30 38 30 30  30 30 30 30 30 38 30 30  |0000080000000800|
00000140  30 30 30 30 30 33 30 30  30 30 30 30 30 30 30 30  |0000030000000000|
00000150  30 30 30 30 30 30 30 30  30 30 30 30 30 44 30 30  |0000000000000D00|
00000160  30 30 30 30 30 30 74 65  73 74 2f 73 79 6d 6c 69  |000000test/symli|
00000170  6e 6b 00 00 66 69 6c 65  2e 74 78 74 30 37 30 37  |nk..file.txt0707|
00000180  30 31 30 30 30 30 30 30  30 30 30 30 30 30 30 30  |0100000000000000|
00000190  30 30 30 30 30 30 30 30  30 30 30 30 30 30 30 30  |0000000000000000|
000001a0  30 30 30 30 30 30 30 30  30 31 30 30 30 30 30 30  |0000000001000000|
000001b0  30 30 30 30 30 30 30 30  30 30 30 30 30 30 30 30  |0000000000000000|
*
000001e0  30 42 30 30 30 30 30 30  30 30 54 52 41 49 4c 45  |0B00000000TRAILE|
000001f0  52 21 21 21 00 00 00 00  00 00 00 00 00 00 00 00  |R!!!............|
00000200

[piranna@Latitude:~/Proyectos/cpio2tar]
 (master) > ./server.js < archive.cpio > archive.tar

[piranna@Latitude:~/Proyectos/cpio2tar]
 (master) > hd archive.tar 
00000000  74 65 73 74 2f 00 00 00  00 00 00 00 00 00 00 00  |test/...........|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000060  00 00 00 00 30 30 30 37  37 35 20 00 30 30 31 37  |....000775 .0017|
00000070  35 30 20 00 30 30 31 37  35 30 20 00 30 30 30 30  |50 .001750 .0000|
00000080  30 30 30 30 30 30 30 20  31 32 37 30 35 34 32 37  |0000000 12705427|
00000090  32 31 34 20 30 31 30 32  34 37 20 00 35 00 00 00  |214 010247 .5...|
000000a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000100  00 75 73 74 61 72 00 30  30 00 00 00 00 00 00 00  |.ustar.00.......|
00000110  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000140  00 00 00 00 00 00 00 00  00 30 30 30 30 31 30 20  |.........000010 |
00000150  00 30 30 30 30 30 33 20  00 00 00 00 00 00 00 00  |.000003 ........|
00000160  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000200  74 65 73 74 2f 66 69 6c  65 2e 74 78 74 00 00 00  |test/file.txt...|
00000210  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000260  00 00 00 00 30 30 30 36  36 34 20 00 30 30 31 37  |....000664 .0017|
00000270  35 30 20 00 30 30 31 37  35 30 20 00 30 30 30 30  |50 .001750 .0000|
00000280  30 30 30 30 30 30 37 20  31 32 37 30 35 34 32 37  |0000007 12705427|
00000290  30 30 36 20 30 31 31 37  32 33 20 00 30 00 00 00  |006 011723 .0...|
000002a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000300  00 75 73 74 61 72 00 30  30 00 00 00 00 00 00 00  |.ustar.00.......|
00000310  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000340  00 00 00 00 00 00 00 00  00 30 30 30 30 31 30 20  |.........000010 |
00000350  00 30 30 30 30 30 33 20  00 00 00 00 00 00 00 00  |.000003 ........|
00000360  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000400  61 20 66 69 6c 65 0a 00  00 00 00 00 00 00 00 00  |a file..........|
00000410  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000600  74 65 73 74 2f 73 79 6d  6c 69 6e 6b 00 00 00 00  |test/symlink....|
00000610  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000660  00 00 00 00 30 30 30 37  37 37 20 00 30 30 31 37  |....000777 .0017|
00000670  35 30 20 00 30 30 31 37  35 30 20 00 30 30 30 30  |50 .001750 .0000|
00000680  30 30 30 30 30 30 30 20  31 32 37 30 35 34 32 37  |0000000 12705427|
00000690  32 30 37 20 30 31 33 33  33 35 20 00 32 66 69 6c  |207 013335 .2fil|
000006a0  65 2e 74 78 74 00 00 00  00 00 00 00 00 00 00 00  |e.txt...........|
000006b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000700  00 75 73 74 61 72 00 30  30 00 00 00 00 00 00 00  |.ustar.00.......|
00000710  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000740  00 00 00 00 00 00 00 00  00 30 30 30 30 31 30 20  |.........000010 |
00000750  00 30 30 30 30 30 33 20  00 00 00 00 00 00 00 00  |.000003 ........|
00000760  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000c00
```

I'll try to find some time to integrate this on NodeOS and let's see if we can generate Docker images :-D

**Comment by luii** [comment]
The build process so far gives me no errors, the cpio2tar part works.
Now i get a error that the userfs cant be found
```bash
{ [Error: EPERM, Operation not permitted 'proc'] errno: 1, code: 'EPERM', path: 'proc', syscall: 'mount' }
Could not find userfs: [Error: PARTUUID=d7da3845-7e88-4930-8ce6-6c4e9d679f07 not exists]
prompt: path to userfs:  [Error: canceled]
readline.js:925
            throw err;
            ^

TypeError: Cannot read property 'path to userfs' of undefined
    at pathToUserfs (/lib/node_modules/nodeos-mount-filesystems/server.js:269:24)
    at /lib/node_modules/nodeos-mount-filesystems/node_modules/prompt/lib/prompt.js:336:20
    at /lib/node_modules/nodeos-mount-filesystems/node_modules/prompt/node_modules/utile/node_modules/async/lib/async.js:148:21
    at assembler (/lib/node_modules/nodeos-mount-filesystems/node_modules/prompt/lib/prompt.js:302:18)
    at /lib/node_modules/nodeos-mount-filesystems/node_modules/prompt/lib/prompt.js:342:20
    at /lib/node_modules/nodeos-mount-filesystems/node_modules/prompt/lib/prompt.js:542:14
    at onError (/lib/node_modules/nodeos-mount-filesystems/node_modules/prompt/node_modules/read/lib/read.js:94:12)
    at Interface.<anonymous> (/lib/node_modules/nodeos-mount-filesystems/node_modules/prompt/node_modules/read/lib/read.js:66:5)
    at emitNone (events.js:67:13)
    at Interface.emit (events.js:166:7)
```

**Comment by piranna** [comment]
Interesting... Are you trying to mount usersfs by using a UUID instead of a
path?

**Comment by luii** [comment]
> Are you trying to mount usersfs by using a UUID instead of a path?

It seems that this happens automaticly

I changed some things to get around the `/proc/mtab` error like the `nodeos-mount-filesystems` which i changed to my forked repo `luii/nodeos-mount-filesystems` in the `packages.txt` in `nodeos-initramfs`

I looked at my build log and saw just now that the userfs was not copied over to `out/latest`

```bash
Successfully generated nodeos user folder
Successfully built Layer-3 image 'usersfs'

> NodeOS@0.0.0 install /home/philipp/Dokumente/github/NodeOS
> scripts/build

cp: Verzeichnis 'node_modules/nodeos-usersfs/out/latest' wurde ausgelassen

> NodeOS@0.0.0 postinstall /home/philipp/Dokumente/github/NodeOS
> scripts/postinstall

------------------------------------------
Success!
You just built a custom NodeOS image
------------------------------------------
```

So i copied the files manully to the `out/latest` folder and made a tar out of it but same result

**Comment by piranna** [comment]
> So i copied the files manully to the out/latest folder and made a tar out
of it but same result

Do you ger the same error? Maybe Docker is trying to mount the filesystem
from other place... So far I only did some experiments with vagga and it
was using /proc/cmdline from the host system so I needed to hack
nodeos-mount-filesystems to override its values with some environment
variables, probably it's happening the same with Docker. Could you confirm
that UUID is the one of your real machine root partition? If so, then now
you know where to start hacking... ;-)

**Comment by luii** [comment]
Unfortunetly they're not the same
![term](https://cloud.githubusercontent.com/assets/8077014/14766789/b4bfbd8e-0a16-11e6-874d-57a5ee22ca06.png)

**Comment by piranna** [comment]
> Unfortunetly they're not the same

Sh*t... :-( Could you be able to post the output of /proc/cmdline? The
error talk about PARTUUID instead of UUID. Partition and filesystem UUIDs
are not necesarily the same and I think lsblk only show filesystem ones
(but maybe there's an option to show paftition ones), so this could be the
problem...

By the way, nice system, 4 hard disks... :-)

**Comment by luii** [comment]
> By the way, nice system, 4 hard disks... :-)

The `sda` and `sdb` are for Windows, since i switched to Arch i havent used them at all (one ssd and a hdd :P )

But it seems you were right about the UUID of the Filesystem and the PARTUUID, they're not the same! Since i use GPT for my System i used the wrong command (`lsblk`) instead of `blkid`.

And like you said above, docker is trying to mount the host root partition XD
`/dev/sdd3: UUID="35ab3572-5266-4480-b756-793eb8b4ead7" TYPE="ext4" PARTLABEL="root" PARTUUID="d7da3845-7e88-4930-8ce6-6c4e9d679f07"`

`Could not find userfs: [Error: PARTUUID=d7da3845-7e88-4930-8ce6-6c4e9d679f07 not exists]`

Do you have any clues how i can override this, because im not nearly so experienced like you with nodeos!

**Comment by piranna** [comment]
> But it seems you were right about the UUID of the Filesystem and the PARTUUID, they're not the same! Since i use GPT for my System i used the wrong command (lsblk) instead of blkid.
> 
> And like you said above, docker is trying to mount the host root partition XD
> /dev/sdd3: UUID="35ab3572-5266-4480-b756-793eb8b4ead7" TYPE="ext4" PARTLABEL="root" PARTUUID="d7da3845-7e88-4930-8ce6-6c4e9d679f07"
> 
> Could not find userfs: [Error: PARTUUID=d7da3845-7e88-4930-8ce6-6c4e9d679f07 not exists]

And we have a winner! :-P


> Do you have any clues how i can override this, because im not nearly so experienced like you with nodeos!

You can set on the `Dockerfile` the environment variable `root` to "container" and [it will by-pass the mount of usersfs](https://github.com/NodeOS/nodeos-mount-filesystems/blob/7937600616a6987d472d0e85d9c4143ec9585c97/server.js#L323-L328) because it should be already mounted by Docker itself. Besides that keep in mind that this is mostly untested because Docker and vagga didn't supported usage of FUSE or OverlayFS inside LXC containers (although seems Docker now support FUSE with some capabilities configuration on the Dockerfile and OverlayFS with a kernel patch that seems Ubuntu has by default), so probably there should be dragons :-P

**Comment by luii** [comment]
Ok that works.
I've now booted into the barebones repl!
```bash
[philipp@arch NodeOS]$ docker run -t -i nodeos
mount: Operation not permitted
{ [Error: EPERM, Operation not permitted 'proc'] errno: 1, code: 'EPERM', path: 'proc', syscall: 'mount' }
Trace: { [Error: ENOENT: no such file or directory, scandir '/tmp'] errno: -2, code: 'ENOENT', syscall: 'scandir', path: '/tmp' }
    at onerror (/lib/node_modules/nodeos-mount-filesystems/server.js:37:13)
    at done (/lib/node_modules/nodeos-mount-filesystems/server.js:225:5)
    at /lib/node_modules/nodeos-mount-filesystems/server.js:231:22
    at FSReqWrap.oncomplete (fs.js:82:15)
Starting REPL session
NodeOS-mount-filesystems> 
```

**Comment by piranna** [comment]
> I've now booted into the barebones repl!

No, you've booted to the NodeOS-mount-filesystems REPL, that's beyond that ;-) Seems it can't be able to find usersfs. Have you configured the Dockerfile to mount it?

**Comment by luii** [comment]
Well i added `ENV root container` to the `nodeos-userfs` Dockerfile

**Comment by piranna** [comment]
Then here start the dragons :-) You need to config it to mount the disk
image or use it as a layer or something... Sorry, I can't help you more at
this moment, I'll try to take a look later, keep me informed of your
progresses.

**Comment by piranna** [comment]
I've taken a look and the Docker '-v' parameter allow to mount host files
and directories on the container, so it would be possible to mount the
filesystem image on /dev/sdb2, for example. Problems are that maybe it
would be needed to create a loopback device on the fly (on the host or by
NodeOS on the container), and that by portability reasons the '-v' flag is
not available on the Dockerfile, but it's possible to do it with Rockerfile
MOUNT command (
https://github.com/grammarly/rocker/blob/master/README.md#mount), so we
could use it instead...

Anyway, usersfs is just an example filesystem and it should be used custom
ones on production, so if '-v' flag works, we could say it on the docs and
use some simple bash scripts to exec it, what do you think?
El 24/4/2016 14:19, "piranna@gmail.com" <piranna@gmail.com> escribió:

Then here start the dragons :-) You need to config it to mount the disk
image or use it as a layer or something... Sorry, I can't help you more at
this moment, I'll try to take a look later, keep me informed of your
progresses.

**Comment by piranna** [comment]
@luii, did you get any progress on that?

**Comment by luii** [comment]
unfortenetly not, sorry im not so experienced

**Comment by piranna** [comment]
Ok, if I have time I'll try to give it a try, problem is that it's difficult to exec Docker in a 32 bits environment (I don't have currently any 64 bits machine available at this moment... :-/)
