### ISSUE TITLE
NodeOS Build Error

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#249]
Hit an error compiling NodeOS:

Compiling init
make: x86_64-nodeos-linux-musl-gcc: Command not found
make: *** [init.o] Error 127
rmdir: failed to remove ‘/home/triplebackslash/Documents/NodeOS/node_modules/nodeos-barebones/build/nocona’: No such file or directory

npm ERR! Linux 3.16.0-73-generic
npm ERR! argv "/home/triplebackslash/.nvm/versions/node/v4.0.0/bin/node" "/home/triplebackslash/.nvm/versions/node/v4.0.0/bin/npm" "install" "--PLATFORM=iso"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! nodeos-barebones@1.0.0-RC1 install: `scripts/build`
npm ERR! Exit status 10
npm ERR! 
npm ERR! Failed at the nodeos-barebones@1.0.0-RC1 install script 'scripts/build'.
npm ERR! This is most likely a problem with the nodeos-barebones package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/build
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeos-barebones
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/triplebackslash/Documents/NodeOS/npm-debug.log

Of course, I'll look into it myself too. Thanks for the hand!

**Comment by luii** [comment]
I've got that too: #248 
This happens everytime i try to build (docker, qemu, etc)

**Comment by piranna** [comment]
Do you get the same with the latest code? I have been doing some changes go
use prebuild-install by default in everything but maybe I didn't get gime
to finish it yey and probably I broke something... :-(

**Comment by piranna** [comment]
Could both of you try again? Seems my latest changes are working on the CI server... I need to fix the publication of new prebuild releases, though.

**Comment by lite20** [comment]
New error:

Compiling Linux
Makefile:340: scripts/Kbuild.include: No such file or directory
/bin/bash: ./scripts/gcc-goto.sh: No such file or directory
Makefile:785: scripts/Makefile.kasan: No such file or directory
Makefile:786: scripts/Makefile.extrawarn: No such file or directory
Makefile:787: scripts/Makefile.ubsan: No such file or directory
make: *** No rule to make target 'scripts/Makefile.ubsan'.  Stop.

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/home/lite/.nvm/versions/node/v4.0.0/bin/node" "/home/lite/.nvm/versions/node/v4.0.0/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! nodeos-barebones@1.0.0-RC1 install: `scripts/build`
npm ERR! Exit status 51
npm ERR! 
npm ERR! Failed at the nodeos-barebones@1.0.0-RC1 install script 'scripts/build'.
npm ERR! This is most likely a problem with the nodeos-barebones package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/build
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeos-barebones
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lite/Documents/NodeOS/npm-debug.log

**Comment by luii** [comment]
This is my error:
```bash
→ npm install                                                                                                                                                                                              [4ee6346]
 
> genext2fs@1.4.1 install /home/philipp/Dokumente/github/NodeOS/node_modules/genext2fs
> prebuild-install -d https://github.com/NodeOS/genext2fs/releases/download/v{version}/{platform}-{arch}.tar.gz || npm run build

sh: prebuild-install: Kommando nicht gefunden.
-
> genext2fs@1.4.1 build /home/philipp/Dokumente/github/NodeOS/node_modules/genext2fs
> scripts/build

aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:37: warning: AC_CACHE_VAL(ac_scanf_can_malloc, ...): suspicious cache-id, must contain _cv_ to be cached
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
m4/ac_func_scanf_can_malloc.m4:10: AC_FUNC_SCANF_CAN_MALLOC is expanded from...
configure.in:37: the top level
configure.in:37: warning: AC_CACHE_VAL(ac_scanf_can_malloc, ...): suspicious cache-id, must contain _cv_ to be cached
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
m4/ac_func_scanf_can_malloc.m4:10: AC_FUNC_SCANF_CAN_MALLOC is expanded from...
configure.in:37: the top level
configure.in:37: warning: AC_CACHE_VAL(ac_scanf_can_malloc, ...): suspicious cache-id, must contain _cv_ to be cached
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
m4/ac_func_scanf_can_malloc.m4:10: AC_FUNC_SCANF_CAN_MALLOC is expanded from...
configure.in:37: the top level
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake line 3936.
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:37: warning: AC_CACHE_VAL(ac_scanf_can_malloc, ...): suspicious cache-id, must contain _cv_ to be cached
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
m4/ac_func_scanf_can_malloc.m4:10: AC_FUNC_SCANF_CAN_MALLOC is expanded from...
configure.in:37: the top level
configure.in:10: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.in:10: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
configure.in:13: installing './compile'
configure.in:10: installing './install-sh'
configure.in:10: installing './missing'
Makefile.am: error: required file './README' not found
Makefile.am: installing './depcomp'
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
parallel-tests: installing './test-driver'
*** automake failed :(

npm ERR! Linux 4.6.2-1-ARCH
npm ERR! argv "/home/philipp/.nvm/versions/node/v4.4.2/bin/node" "/home/philipp/.nvm/versions/node/v4.4.2/bin/npm" "run" "build"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! genext2fs@1.4.1 build: `scripts/build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the genext2fs@1.4.1 build script 'scripts/build'.
npm ERR! This is most likely a problem with the genext2fs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs genext2fs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls genext2fs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/philipp/Dokumente/github/NodeOS/node_modules/genext2fs/npm-debug.log
 
> nodeos-cross-toolchain@0.0.1 install /home/philipp/Dokumente/github/NodeOS/node_modules/nodeos-cross-toolchain
> prebuild-install --download https://github.com/NodeOS/nodeos-cross-toolchain/releases/download/v{version}/{platform}-{arch}.tar.gz || npm run build

sh: prebuild-install: Kommando nicht gefunden.
-
> nodeos-cross-toolchain@0.0.1 build /home/philipp/Dokumente/github/NodeOS/node_modules/nodeos-cross-toolchain
> scripts/preinstall && scripts/build

module.js:327
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/philipp/Dokumente/github/NodeOS/node_modules/nodeos-cross-toolchain/scripts/preinstall:5:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

npm ERR! Linux 4.6.2-1-ARCH
npm ERR! argv "/home/philipp/.nvm/versions/node/v4.4.2/bin/node" "/home/philipp/.nvm/versions/node/v4.4.2/bin/npm" "run" "build"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! nodeos-cross-toolchain@0.0.1 build: `scripts/preinstall && scripts/build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodeos-cross-toolchain@0.0.1 build script 'scripts/preinstall && scripts/build'.
npm ERR! This is most likely a problem with the nodeos-cross-toolchain package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/preinstall && scripts/build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodeos-cross-toolchain
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls nodeos-cross-toolchain
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/philipp/Dokumente/github/NodeOS/node_modules/nodeos-cross-toolchain/npm-debug.log
-
> qemu@2.6.0 install /home/philipp/Dokumente/github/NodeOS/node_modules/qemu
> prebuild-install -d https://github.com/NodeOS/qemu/releases/download/v{version}/{platform}-{arch}.tar.gz || npm run build

-
> genfatfs@1.0.1 install /home/philipp/Dokumente/github/NodeOS/node_modules/genfatfs
> prebuild-install -d https://github.com/NodeOS/genfatfs/releases/download/v{version}/{platform}-{arch}.tar.gz || npm run build

npm ERR! Linux 4.6.2-1-ARCH
npm ERR! argv "/home/philipp/.nvm/versions/node/v4.4.2/bin/node" "/home/philipp/.nvm/versions/node/v4.4.2/bin/npm" "install"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE

npm ERR! genext2fs@1.4.1 install: `prebuild-install -d https://github.com/NodeOS/genext2fs/releases/download/v{version}/{platform}-{arch}.tar.gz || npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the genext2fs@1.4.1 install script 'prebuild-install -d https://github.com/NodeOS/genext2fs/releases/download/v{version}/{platform}-{arch}.tar.gz || npm run build'.
npm ERR! This is most likely a problem with the genext2fs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install -d https://github.com/NodeOS/genext2fs/releases/download/v{version}/{platform}-{arch}.tar.gz || npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs genext2fs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls genext2fs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/philipp/Dokumente/github/NodeOS/npm-debug.log

```

**Comment by luii** [comment]
clicked the wrong button sorry

**Comment by piranna** [comment]
Try executing first 'npm install --ignore-scripts' to only download the
dependencies, npm2 is not determinist about the order they are execured.

**Comment by luii** [comment]
First got this after i executed it:

```bash
> nodeos-barebones@1.0.0-RC1 install /home/philipp/Dokumente/github/NodeOS/node_modules/nodeos-barebones
> scripts/build

module.js:327
    throw err;
    ^

Error: Cannot find module 'nodejs'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:409:26)
    at node.js:579:27
    at nextTickCallbackWith0Args (node.js:420:9)
Compiling init
make: x86_64-nodeos-linux-musl-gcc: Kommando nicht gefunden
<eingebaut>: die Regel für Ziel „init.o“ scheiterte
make: *** [init.o] Fehler 127
rmdir: konnte '/home/philipp/Dokumente/github/NodeOS/node_modules/nodeos-barebones/build/nocona' nicht entfernen: Datei oder Verzeichnis nicht gefunden
```

Then i installed NodeOS/nodejs

and got only this:
```bash
> nodeos-barebones@1.0.0-RC1 install /home/philipp/Dokumente/github/NodeOS/node_modules/nodeos-barebones
> scripts/build

Compiling init
make: x86_64-nodeos-linux-musl-gcc: Kommando nicht gefunden
<eingebaut>: die Regel für Ziel „init.o“ scheiterte
make: *** [init.o] Fehler 127
rmdir: konnte '/home/philipp/Dokumente/github/NodeOS/node_modules/nodeos-barebones/build/nocona' nicht entfernen: Datei oder Verzeichnis nicht gefunden
```

**Comment by piranna** [comment]
This will be fixed on the RC2.
