### ISSUE TITLE
mount procfs/devtmpfs: Operation not permitted

### ISSUE THREAD

**Issue by luii** [NodeOS/NodeOS#272]
As stated in the PR #266 i get following errors:
```bash
> NodeOS@1.0.0-RC2 docker /home/philipp/Dokumente/NodeOS
> scripts/docker

mount procfs: Operation not permitted
mount devtmpfs: Operation not permitted
Could not find userfs: Error: PARTUUID=d7da3845-7e88-4930-8ce6-6c4e9d679f07 not exists
```

> mount procfs: Operation not permitted
> mount devtmpfs: Operation not permitted

@piranna These errors come from `nodeos-init` since docker takes the hostfs it could not mount them twice, would it be possible to exclude `nodeos-init` for docker?

**Comment by piranna** [comment]
> @piranna These errors come from nodeos-init since docker takes the hostfs it could not mount them twice, would it be possible to exclude nodeos-init for docker?

Yes and no.

`nodeos-init` do several tasks, like collect orphaned child process (its main function), mount `procfs` and `devfs` for Node.js, start the boot process (done by `nodeos-mount-filesystems) and cleanly shutdown the system when there's no more running processes. It can be possible to remove `nodeos-init` and directly exec `nodeos-mount-filesystems`, but in this case there would be no process to collect the orphan child processes, or at least Docker didn't have this functionality in the pass (vagga has a init-like process as PID1 enabled by default). If you can confirm me that Docker has now this functionality or a workaround for it we could remove it, but if not, since that errors don't affect the general boot workflow and only [show some warning messages](https://github.com/piranna/nodeos-init/blob/d91e2052ee78dd004515e04d0796d76081840b47/init.c#L225-L230) (similar to the ones when [don't having permissions to unmount the filesystems](https://github.com/piranna/nodeos-init/blob/d91e2052ee78dd004515e04d0796d76081840b47/init.c#L134)) I would not remove it from the boot process.

**Comment by piranna** [comment]
Another option would be to use [tini](https://github.com/krallin/tini) on Docker, since it seems to behave mostly like `nodeos-init` but without the filesystems mounting and the clean shutdown.

**Comment by zaoqi** [comment]
```
zaoqi@dzeaboiqain:~$ sudo apt install docker-ce -y
[sudo] zaoqi 的密码：
对不起，请重试。
[sudo] zaoqi 的密码：
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
docker-ce 已经是最新版 (5:18.09.2~3-0~debian-stretch)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
zaoqi@dzeaboiqain:~$ sudo docker run -t -i nodeos/nodeos
Unable to find image 'nodeos/nodeos:latest' locally
latest: Pulling from nodeos/nodeos
94a50c750e92: Pull complete 
cc815e2e56f5: Pull complete 
b59c556bab11: Pull complete 
Digest: sha256:be4ab273faeb9dd296a3dd161d1a16faa7e9a1f15c948649070c4f4818bc708f
Status: Downloaded newer image for nodeos/nodeos:latest
mount procfs: Operation not permitted
mount devtmpfs: Operation not permitted
Trace: { Error: EPERM, Operation not permitted 'overlay'
    at Error (native) errno: 1, code: 'EPERM', path: 'overlay', syscall: 'mount' }
    at onerror (/lib/node_modules/nodeos-boot-multiUser/server.js:23:11)
    at /lib/node_modules/nodeos-boot-multiUser/server.js:46:26
    at /lib/node_modules/nodeos-boot-multiUser/lib/index.js:97:24
    at /lib/node_modules/nodeos-boot-multiUser/lib/jocker_root.js:198:24
Starting REPL session
NodeOS-boot-multiuser> 
```

**Comment by zaoqi** [comment]
```
NodeOS-boot-multiuser> Got "exit" event from repl!
/sys/firmware: Operation not permitted
/proc/sched_debug: Operation not permitted
/proc/timer_list: Operation not permitted
/proc/keys: Operation not permitted
/proc/kcore: Operation not permitted
/proc/acpi: Operation not permitted
/proc/asound: Operation not permitted
/proc/sysrq-trigger: Operation not permitted
/proc/sys: Operation not permitted
/proc/irq: Operation not permitted
/proc/fs: Operation not permitted
/proc/bus: Operation not permitted
/dev/console: Operation not permitted
/dev/shm: Operation not permitted
/etc/hosts: Operation not permitted
/etc/hostname: Operation not permitted
/etc/resolv.conf: Operation not permitted
/tmp: Operation not permitted
/dev/mqueue: Operation not permitted
/sys/fs/cgroup/perf_event: Operation not permitted
/sys/fs/cgroup/memory: Operation not permitted
/sys/fs/cgroup/devices: Operation not permitted
/sys/fs/cgroup/freezer: Operation not permitted
/sys/fs/cgroup/net_cls,net_prio: Operation not permitted
/sys/fs/cgroup/blkio: Operation not permitted
/sys/fs/cgroup/cpu,cpuacct: Operation not permitted
/sys/fs/cgroup/pids: Operation not permitted
/sys/fs/cgroup/cpuset: Operation not permitted
/sys/fs/cgroup/systemd: Operation not permitted
/sys/fs/cgroup: Operation not permitted
/sys: Operation not permitted
/dev/pts: Operation not permitted
/dev: Operation not permitted
/proc: Operation not permitted
/: Operation not permitted
termination: Operation not permitted
zaoqi@dzeaboiqain:~$ 
```

**Comment by PeterHindes** [comment]
I have the same error on windows 10
