### ISSUE TITLE
Ghost Build Error

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#305]
I got an error attempting to build NodeOS. This error doesn't give any information I can recognize and infact, I don't see a warning or error at all... it just fails. Now, it could be because I'm tired but I did run "npm install" and this error occured with "npm run build". Here's the npm-debug.log

`0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v6.3.1/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v6.3.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle NodeOS@1.0.0-RC2~prebuild: NodeOS@1.0.0-RC2
6 silly lifecycle NodeOS@1.0.0-RC2~prebuild: no script for prebuild, continuing
7 info lifecycle NodeOS@1.0.0-RC2~build: NodeOS@1.0.0-RC2
8 verbose lifecycle NodeOS@1.0.0-RC2~build: unsafe-perm in lifecycle true
9 verbose lifecycle NodeOS@1.0.0-RC2~build: PATH: /root/.nvm/versions/node/v6.3.1/lib/node_modules/npm/bin/node-gyp-bin:/root/nodeos/node_modules/.bin:/root/.nvm/versions/node/v6.3.1/bin:/root/.nvm/versions/node/v6.3.1/bin:/root/bin:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle NodeOS@1.0.0-RC2~build: CWD: /root/nodeos
11 silly lifecycle NodeOS@1.0.0-RC2~build: Args: [ '-c', 'scripts/build' ]
12 silly lifecycle NodeOS@1.0.0-RC2~build: Returned: code: 1  signal: null
13 info lifecycle NodeOS@1.0.0-RC2~build: Failed to exec build script
14 verbose stack Error: NodeOS@1.0.0-RC2 build:`scripts/build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v6.3.1/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v6.3.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid NodeOS@1.0.0-RC2
16 verbose cwd /root/nodeos
17 error Linux 4.4.0-31-generic
18 error argv "/root/.nvm/versions/node/v6.3.1/bin/node" "/root/.nvm/versions/node/v6.3.1/bin/npm" "run" "build"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error NodeOS@1.0.0-RC2 build:`scripts/build`
22 error Exit status 1
23 error Failed at the NodeOS@1.0.0-RC2 build script 'scripts/build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the NodeOS package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     scripts/build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs NodeOS
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls NodeOS
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by piranna** [comment]
It's strange, seems that scripts/build fails just when it start to exec...

El 13/9/2016 6:09, "Lite McFish" <notifications@github.com> escribió:

I got an error attempting to build NodeOS. This error doesn't give any
information I can recognize and infact, I don't see a warning or error at
all... it just fails. Now, it could be because I'm tired but I did run "npm
install" and this error occured with "npm run build". Here's the
npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v6.3.1/bin/node',
1 verbose cli '/root/.nvm/versions/node/v6.3.1/bin/npm',
1 verbose cli 'run',
1 verbose cli 'build' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle NodeOS@1.0.0-RC2~prebuild: NodeOS@1.0.0-RC2
6 silly lifecycle NodeOS@1.0.0-RC2~prebuild: no script for prebuild,
continuing
7 info lifecycle NodeOS@1.0.0-RC2~build: NodeOS@1.0.0-RC2
8 verbose lifecycle NodeOS@1.0.0-RC2~build: unsafe-perm in lifecycle true
9 verbose lifecycle NodeOS@1.0.0-RC2~build: PATH:
/root/.nvm/versions/node/v6.3.1/lib/node_modules/npm/bin/
node-gyp-bin:/root/nodeos/node_modules/.bin:/root/.nvm/
versions/node/v6.3.1/bin:/root/.nvm/versions/node/v6.3.
1/bin:/root/bin:/root/.local/bin:/usr/local/sbin:/usr/
local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/
local/games:/snap/bin
10 verbose lifecycle NodeOS@1.0.0-RC2~build: CWD: /root/nodeos
11 silly lifecycle NodeOS@1.0.0-RC2~build: Args: [ '-c', 'scripts/build' ]
12 silly lifecycle NodeOS@1.0.0-RC2~build: Returned: code: 1 signal: null
13 info lifecycle NodeOS@1.0.0-RC2~build: Failed to exec build script
14 verbose stack Error: NodeOS@1.0.0-RC2 build:scripts/build
14 verbose stack Exit status 1
14 verbose stack at EventEmitter.<anonymous> (/root/.nvm/versions/node/v6.
3.1/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack at emitTwo (events.js:106:13)
14 verbose stack at EventEmitter.emit (events.js:191:7)
14 verbose stack at ChildProcess.<anonymous> (/root/.nvm/versions/node/v6.
3.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack at emitTwo (events.js:106:13)
14 verbose stack at ChildProcess.emit (events.js:191:7)
14 verbose stack at maybeClose (internal/child_process.js:852:16)
14 verbose stack at Process.ChildProcess._handle.onexit
(internal/child_process.js:215:5)
15 verbose pkgid NodeOS@1.0.0-RC2
16 verbose cwd /root/nodeos
17 error Linux 4.4.0-31-generic
18 error argv "/root/.nvm/versions/node/v6.3.1/bin/node"
"/root/.nvm/versions/node/v6.3.1/bin/npm" "run" "build"
19 error node v6.3.1
20 error npm v3.10.3
21 error code ELIFECYCLE
22 error NodeOS@1.0.0-RC2 build:scripts/build
22 error Exit status 1
23 error Failed at the NodeOS@1.0.0-RC2 build script 'scripts/build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the NodeOS package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error scripts/build
23 error You can get information on how to open an issue for this project
with:
23 error npm bugs NodeOS
23 error Or if that isn't available, you can get their info via:
23 error npm owner ls NodeOS
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NodeOS/NodeOS/issues/305>, or mute the thread

**Comment by lite20** [comment]
What could cause a crash that quick? Will you need more of my device specs?

**Comment by piranna** [comment]
Look what's generating the exit 1 on scripts/build.

**Comment by luii** [comment]
Des this still exists in the RC3.3 Version?

**Comment by luii** [comment]
closing due to inactivity.
