### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by johnroper100** [NodeOS/NodeOS#310]
Hi, I built nodeos using the instructions on the website. Everything build fine, but when I go to run *npm start* I get this error:
```fs.js:1014
  return binding.readlink(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, readlink 'out/latest'
    at Error (native)
    at Object.fs.readlinkSync (fs.js:1014:18)
    at Object.<anonymous> (/home/johnroper100/NodeOS/scripts/start:11:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

I looked in the files, and there is not a folder named *out* anywhere.

**Comment by luii** [comment]
Try `npm install` first on a fresh clone and then `npm run build`, the instructions are a little bit outdated.

**Comment by piranna** [comment]
It should be fixed in master, sorry for the delay. Clossing.
