### ISSUE TITLE
user init script not starting due to an error

### ISSUE THREAD

**Issue by tinkabellelisa** [NodeOS/NodeOS#347]
Trace: Error: /tmp/dev not mounted
 at /lib/node_modules/nodeos-boot-multiUser/lib/jocker_root.js:78:38
 at FSRwqWrap.oncomplete (fs.js:123:15)
 at oneerror (/lib/node_modules/nodeos-boot-multiUser/server.js:23:11)
 at /lib/node_modules/nodeos-boot-multiUser/server.js:46:26
 at /lib/node_modules/nodeos-boot-multiUser/lib/index.js:97:24
 at /lib/node_modules/nodeos-boot-multiUser/lib/jocker_root.js:219:28
 at /lib/node_modules/nodeos-boot-multiUser/lib/jocker_root.js:142.26
 at /lib/node_modules/nodeos-boot-multiUser/lib/jocker_root.js:78:29
 at FSReqWrap.oncomplete (fs.js:123:15)
Starting REPL session
NodeOS-boot-multiuser>

**Comment by tinkabellelisa** [comment]
![screenshot from 2017-04-09 10 26 22](https://cloud.githubusercontent.com/assets/27082873/24834917/f0782cbe-1d0f-11e7-97e4-8df5d360789c.png)

**Comment by skompc** [comment]
Im having the same issue... is it fixed yet?

**Comment by piranna** [comment]
There have been some changes and improvements lately, so recent prebuild images should have it already fixed. Can you confirm that?

**Comment by skompc** [comment]
I just tried it and the most recent prebuild image still has the error

**Comment by piranna** [comment]
I'll need to review it, lately I'm having spare time to dedicate to the project, any help on this area will be greatly welcome.

**Comment by skompc** [comment]
Im only able to test it in qemu... specifically limbo on android... ive tried all possibe configurations and releases files for the latest build... is there an earlier version that doesnt display this error?... and im glad to help in any way im able (probably just testing and suggestions)

**Comment by luii** [comment]
@skompc do you still have this error in the newest version?

**Comment by skompc** [comment]
I'll be able to answer that in a couple weeks. I'm afk for a month. Phone
only.
