### ISSUE TITLE
Error: EINVAL: invalid argument, readlink 'out/latest'

### ISSUE THREAD

**Issue by LoganDark** [NodeOS/NodeOS#349]
```
> NodeOS@1.0.0-RC3 start /Users/LoganDark/NodeOS
> scripts/start

fs.js:972
  return binding.readlink(pathModule._makeLong(path), options.encoding);
                 ^

Error: EINVAL: invalid argument, readlink 'out/latest'
    at Object.fs.readlinkSync (fs.js:972:18)
    at Object.<anonymous> (/Users/LoganDark/NodeOS/scripts/start:20:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/LoganDark/.nvm/versions/node/v7.6.0/bin/node" "/Users/LoganDark/.nvm/versions/node/v7.6.0/bin/npm" "start"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! NodeOS@1.0.0-RC3 start: `scripts/start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the NodeOS@1.0.0-RC3 start script 'scripts/start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the NodeOS package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs NodeOS
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls NodeOS
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/LoganDark/NodeOS/npm-debug.log
```

after running `npm start` with the latest NodeOS which I built on my server and then transferred to my local machine.

**Comment by luii** [comment]
Could you check if you copied the symlinks that the build created, because some filemanagers dont copy 0 Byte files (symlinks) they just discard them

**Comment by LoganDark** [comment]
I used `zip` and `unzip` from the terminal.
