### ISSUE TITLE
/bin/getty /bin/logon: "/bin/getty" exited with code 1

### ISSUE THREAD

**Issue by luii** [NodeOS/NodeOS#385]
@piranna After i build the usersfs and build everything else i started it with `npm start` and got this:
`/bin/getty /bin/logon: "/bin/getty" exited with code 1` after everything started, the funny is i don't know from where this originiated, because getty dont has such a error message

**Comment by piranna** [comment]
error code 1 is usually the standard error to say something went wrong, so it could be generated by other thing, maybe logon itself

**Comment by luii** [comment]
but it only occours when i try to install nodeos-git.

```bash
INSTALL_NODEGIT='BUILD_ONLY=1      \
       npm_config_prefix=$STEP_DIR \
       npm install                 \
        --production               \
        --arch=$NODE_ARCH          \
        --nodedir=$NODE_DIR        \
        --jobs=$JOBS -g luii/nodeos-git#next'
```

```bash
NPMi='CC=$TARGET-gcc              \ <--
      CXX=$TARGET-g++                \
      npm_config_prefix=$STEP_DIR \
      npm install                 \
        --production              \
        --quiet --no-spin         \
        --arch=$NODE_ARCH         \
        --nodedir=$NODE_DIR       \
        --jobs=$JOBS              '
```

if i dont run it after `nodeosDependenciesNodeos` then everything is ok.
but if i add this code up above and add `eval "$INSTALL_NODEGIT"` i get the error from the title.
so i think it has something to do that i left out the `CC` and `CXX` environment variables.
Because if i add the `CC` and `CXX` i get this error:

```bash
[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/openssl/openssl
/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/libssh2':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/openssl/openssl' }
/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/libssh2':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/openssl/openssl
/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/libssh2':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib/node_modules/nodeos-git/node_modules/nodegit/vendor/openssl/openssl' }
/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/nodeos/lib
└── (empty)
```

**Comment by piranna** [comment]
You need to compile it with the cross-compiler, if not you'll be merging libraries and binaries for several standard lubraries (glibc and musl), thst probably is the source of the problem. Try to compile nodeos-git using the cross-toolchain in a standalone fashion first instead of compile the full usersfs.

**Comment by luii** [comment]
Sounds like an good option to do

**Comment by luii** [comment]
@piranna offtopic: could you invite me to the "nodeos" organization on npm that i can publish packages for nodeos under the nodeos scope.

**Comment by piranna** [comment]
What's your npm username?

**Comment by luii** [comment]
luii like the github username

**Comment by piranna** [comment]
Done :-)

**Comment by luii** [comment]
Im making good progress here and already pushed most of the script to [luii/nodeos-nodegit](https://github.com/luii/nodeos-nodegit)

**Comment by luii** [comment]
Error only happens on wrong compile modules somehow, so im closing because it is resolved with the Version `nodeos-nodegit`
