### ISSUE TITLE
ERR! build error

### ISSUE THREAD

**Issue by sachinbanugariya** [NodeOS/NodeOS#434]
## Description
build not complited gives errors

## Screenshots or Log
root@test:~/NodeOS# npm install

> node-pty@0.6.10 install /root/NodeOS/node_modules/node-pty
> node scripts/install.js

make: Entering directory '/root/NodeOS/node_modules/node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
pty.target.mk:101: recipe for target 'Release/obj.target/pty/src/unix/pty.o' failed
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 127
make: Leaving directory '/root/NodeOS/node_modules/node-pty/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/NodeOS/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-64-generic
gyp ERR! command "/usr/bin/node" "/root/NodeOS/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /root/NodeOS/node_modules/node-pty
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
NodeOS@1.0.0-RC3 /root/NodeOS
└── (empty)

npm ERR! Linux 4.15.0-64-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! node-pty@0.6.10 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.6.10 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/NodeOS/npm-debug.log
npm ERR! code 1

## Steps to Reproduce

1. fresh install ubuntu 18
2. install git and npm
3. clone repo of nodeos
4. inside repo first step : bin/install-dependencies
5. second step: npm install >> gives error, which pasted above.

## Context

npm install

## Your Environment

* Operating System used: ubuntu 18
* Platform used: linux
* Node Version used (locally): v8.10.0
* NPM Version used (locally): 3.5.2
* NodeOS Version used: lastest cloned
* Special Environment Variables used: 
* Link to your project:

**Comment by RossComputerGuy** [comment]
This is an issue with node-pty

**Comment by sachinbanugariya** [comment]
Yes but how can i go ahead and fix this?
Can you please let me know??
Thanks

**Comment by RossComputerGuy** [comment]
Edit the package.json file for the package that failed and change it to Microsoft's version https://github.com/microsoft/node-pty

**Comment by sachinbanugariya** [comment]
Ok thanks i will check it soon,
Btw I'm using it in ubuntu 18, then also need to change for Microsoft??

**Comment by RossComputerGuy** [comment]
No, Microsoft's fork of node-pty works on any OS that supports Node.JS. You should also run `npm install` after editing the package.json files.

**Comment by sachinbanugariya** [comment]
Ok thank you so much.
I will check it soon and let you know.
Thanks

**Comment by sachinbanugariya** [comment]
8529 silly install nodeos-initramfs@1.0.0-RC3.2 /root/NodeOS/node_modules/.staging/nodeos-initramfs-bc79ef8c
28530 info lifecycle nodeos-initramfs@1.0.0-RC3.2~install: nodeos-initramfs@1.0.0-RC3.2
28531 verbose lifecycle nodeos-initramfs@1.0.0-RC3.2~install: unsafe-perm in lifecycle false
28532 verbose lifecycle nodeos-initramfs@1.0.0-RC3.2~install: PATH: /usr/share/npm/bin/node-gyp-bin:/root/NodeOS/node_modules/nodeos-initramfs/node_modules/.bin:/root/NodeOS/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
28533 verbose lifecycle nodeos-initramfs@1.0.0-RC3.2~install: CWD: /root/NodeOS/node_modules/nodeos-initramfs
28534 silly lifecycle nodeos-initramfs@1.0.0-RC3.2~install: Args: [ '-c',
28534 silly lifecycle   '(prebuild-install -d https://github.com/NodeOS/nodeos-initramfs/releases/download/v{version}/{platform}-{arch}.tar.gz && scripts/checkOut) || (buildDependencies && npm run build)' ]
28535 silly lifecycle nodeos-initramfs@1.0.0-RC3.2~install: Returned: code: 1  signal: null
28536 info lifecycle nodeos-initramfs@1.0.0-RC3.2~install: Failed to exec install script
28537 verbose unlock done using /root/.npm/_locks/staging-300fbd9146f52355.lock for /root/NodeOS/node_modules/.staging
28538 silly rollbackFailedOptional Starting
28539 silly rollbackFailedOptional Finishing
28540 silly runTopLevelLifecycles Starting
28541 silly runTopLevelLifecycles Finishing
28542 silly install printInstalled
28543 verbose stack Error: nodeos-initramfs@1.0.0-RC3.2 install: `(prebuild-install -d https://github.com/NodeOS/nodeos-initramfs/releases/download/v{version}/{platform}-{arch}.tar.gz && scripts/checkOut) || (buildDependencies && npm run build)`
28543 verbose stack Exit status 1
28543 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
28543 verbose stack     at emitTwo (events.js:126:13)
28543 verbose stack     at EventEmitter.emit (events.js:214:7)
28543 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
28543 verbose stack     at emitTwo (events.js:126:13)
28543 verbose stack     at ChildProcess.emit (events.js:214:7)
28543 verbose stack     at maybeClose (internal/child_process.js:925:16)
28543 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
28544 verbose pkgid nodeos-initramfs@1.0.0-RC3.2
28545 verbose cwd /root/NodeOS
28546 error Linux 4.15.0-64-generic
28547 error argv "/usr/bin/node" "/usr/bin/npm" "install"
28548 error node v8.10.0
28549 error npm  v3.5.2
28550 error code ELIFECYCLE
28551 error nodeos-initramfs@1.0.0-RC3.2 install: `(prebuild-install -d https://github.com/NodeOS/nodeos-initramfs/releases/download/v{version}/{platform}-{arch}.tar.gz && scripts/checkOut) || (buildDependencies && npm run build)`
28551 error Exit status 1
28552 error Failed at the nodeos-initramfs@1.0.0-RC3.2 install script '(prebuild-install -d https://github.com/NodeOS/nodeos-initramfs/releases/download/v{version}/{platform}-{arch}.tar.gz && scripts/checkOut) || (buildDependencies && npm run build)'.
28552 error Make sure you have the latest version of node.js and npm installed.
28552 error If you do, this is most likely a problem with the nodeos-initramfs package,
28552 error not with npm itself.
28552 error Tell the author that this fails on your system:
28552 error     (prebuild-install -d https://github.com/NodeOS/nodeos-initramfs/releases/download/v{version}/{platform}-{arch}.tar.gz && scripts/checkOut) || (buildDependencies && npm run build)
28552 error You can get information on how to open an issue for this project with:
28552 error     npm bugs nodeos-initramfs
28552 error Or if that isn't available, you can get their info via:
28552 error     npm owner ls nodeos-initramfs
28552 error There is likely additional logging output above.
28553 verbose exit [ 1, true ]


above error getting now.

**Comment by RossComputerGuy** [comment]
It looks like a permission error for locking `/root/.npm/_locks/staging-300fbd9146f52355.lock`, I don't know why its doing that.
