### ISSUE TITLE
Docker error at start

### ISSUE THREAD

**Issue by yhojann-cl** [NodeOS/NodeOS#447]
```
whk@machine:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
whk@machine:~$ sudo docker run -t -i nodeos/nodeos
[sudo] contraseña para whk: 
Unable to find image 'nodeos/nodeos:latest' locally
latest: Pulling from nodeos/nodeos
94a50c750e92: Pull complete 
cc815e2e56f5: Pull complete 
b59c556bab11: Pull complete 
Digest: sha256:be4ab273faeb9dd296a3dd161d1a16faa7e9a1f15c948649070c4f4818bc708f
Status: Downloaded newer image for nodeos/nodeos:latest
mount procfs: Operation not permitted
mount devtmpfs: Operation not permitted
Trace: { Error: EPERM, Operation not permitted 'overlay'
    at Error (native) errno: 1, code: 'EPERM', path: 'overlay', syscall: 'mount' }
    at onerror (/lib/node_modules/nodeos-boot-multiUser/server.js:23:11)
    at /lib/node_modules/nodeos-boot-multiUser/server.js:46:26
    at /lib/node_modules/nodeos-boot-multiUser/lib/index.js:97:24
    at /lib/node_modules/nodeos-boot-multiUser/lib/jocker_root.js:198:24
Starting REPL session
NodeOS-boot-multiuser>
```

**Comment by fearlessgeekmedia** [comment]
I'm having the same problem here. Any fix for it?

**Comment by reisenbauer** [comment]
this helps:
docker run **--cap-add=SYS_ADMIN** -t -i nodeos/nodeos

**Comment by fearlessgeekmedia** [comment]
That didn't help me. I'm getting this now, so slightly different. 

Unable to find image 'nodeos/nodeos:latest' locally
latest: Pulling from nodeos/nodeos
94a50c750e92: Already exists 
cc815e2e56f5: Already exists 
b59c556bab11: Already exists 
Digest: sha256:be4ab273faeb9dd296a3dd161d1a16faa7e9a1f15c948649070c4f4818bc708f
Status: Downloaded newer image for nodeos/nodeos:latest
fuse: failed to open /dev/fuse: Operation not permitted
ExclFS failed to mount: Error: Mount failed
    at ops.error (/lib/node_modules/exclfs/node_modules/fuse-bindings/index.js:61:14)
Trace: Error: /tmp/dev not mounted
    at /lib/node_modules/nodeos-boot-multiUser/lib/jocker_root.js:78:38
    at FSReqWrap.oncomplete (fs.js:123:15)
    at onerror (/lib/node_modules/nodeos-boot-multiUser/server.js:23:11)
    at /lib/node_modules/nodeos-boot-multiUser/server.js:46:26
    at /lib/node_modules/nodeos-boot-multiUser/lib/index.js:97:24
    at /lib/node_modules/nodeos-boot-multiUser/lib/jocker_root.js:219:28
    at /lib/node_modules/nodeos-boot-multiUser/lib/jocker_root.js:142:26
    at /lib/node_modules/nodeos-boot-multiUser/lib/jocker_root.js:78:29
    at FSReqWrap.oncomplete (fs.js:123:15)
Starting REPL session
NodeOS-boot-multiuser>
