### ISSUE TITLE
Crash when creating anonymous function.

### ISSUE THREAD

**Issue by Wazzaps** [NodeOS/NodeOS#72]
So I was thinking this was a node REPL, but i guess it's not, because when I tried a simple JS thing:

``` javascript
(function(){return 5})()
```

But then it crashed on me:

```
/root/lib/node_modules/bin-nsh/node_modules/lib-cmdparse/index.js:15
    if (env && item[0] != '-' && item.indexOf('=') > 0) {
                                      ^
TypeError: Object #<Object> has no method 'indexOf'
    at /root/lib/node_modules/bin-nsh/node_modules/lib-cmdparse/index.js:15:39
    at Array.forEach (native)
    at parse (/root/lib/node_modules/bin-nsh/node_modules/lib-cmdparse/index.js:13:9)
    at run (/root/lib/node_modules/bin-nsh/nsh.js:123:16)
    at readline (/root/lib/node_modules/bin-nsh/nsh.js:93:7)
    at /root/lib/node_modules/bin-nsh/nsh.js:176:5
    at Interface._onLine (readline.js:200:5)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
<---- first runner exited
<---- stopping init because BOOT=0 (set BOOT=1 to override)
docker@boot2docker:~$
```

I have a feeling this isn't intended behaviour.
Uhh, bug report?

**Comment by lite20** [comment]
status?
