### ISSUE TITLE
Tar error on npm install

### ISSUE THREAD

**Issue by zodern** [NodeOS/NodeOS#91]
I have tried building Node OS a few times the past several weeks, but it always ends in an error with tar.  Using the latest comments on master when I run npm install I get this, which is the furthest it has gotten for me:

```
$ sudo npm install
npm WARN package.json nodeos-barebones@0.0.0 No repository field.
npm WARN package.json nodeos-rootfs@0.0.0 No repository field.
npm WARN package.json nodeos-initramfs@0.0.0 No repository field.
npm WARN package.json nodeos-usersfs@0.0.0 No repository field.

> nodeos-barebones@0.0.0 preinstall /Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones
> scripts/preinstall

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16.4M  100 16.4M    0     0   446k      0  0:00:37  0:00:37 --:--:--  472k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1247  100  1247    0     0   1361      0 --:--:-- --:--:-- --:--:--  2322
patching file ui_openssl.c

> nodeos-cross-toolchain@0.0.0 preinstall /Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain
> scripts/preinstall

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29.3M  100 29.3M    0     0   607k      0  0:00:49  0:00:49 --:--:--  339k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  101M  100  101M    0     0   473k      0  0:03:39  0:03:39 --:--:-- 1898k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26649  100 26649    0     0   6095      0  0:00:04  0:00:04 --:--:-- 93834
patching file libstdc++-v3/configure.host
Hunk #1 succeeded at 243 (offset -21 lines).
Hunk #2 succeeded at 258 (offset -21 lines).
patching file gcc/config.gcc
patching file gcc/config/linux.h
patching file gcc/config/linux.opt
patching file gcc/ginclude/stddef.h
patching file libgomp/config/posix/time.c
patching file libgcc/unwind-dw2-fde-dip.c
patching file gcc/configure
Hunk #1 succeeded at 26787 (offset 51 lines).
Hunk #2 succeeded at 26823 (offset 51 lines).
Hunk #3 succeeded at 26906 (offset 51 lines).
patching file gcc/configure.ac
Hunk #1 succeeded at 4664 (offset -55 lines).
Hunk #2 succeeded at 4700 (offset -55 lines).
Hunk #3 succeeded at 4766 (offset -55 lines).
patching file fixincludes/mkfixinc.sh
Hunk #1 succeeded at 20 (offset 1 line).
patching file config.sub
patching file gcc/config/i386/linux.h
Hunk #1 succeeded at 22 (offset 1 line).
patching file gcc/config/i386/linux64.h
Hunk #1 succeeded at 31 (offset 1 line).
patching file libitm/config/linux/x86/tls.h
patching file gcc/config/arm/linux-eabi.h
patching file libitm/config/arm/hwcap.cc
patching file gcc/config/mips/linux.h
Hunk #1 succeeded at 19 (offset 1 line).
patching file gcc/config.gcc
Hunk #1 succeeded at 2095 (offset -17 lines).
patching file gcc/config/rs6000/linux64.h
Hunk #1 succeeded at 362 (offset -2 lines).
patching file gcc/config/rs6000/secureplt.h
patching file gcc/config/rs6000/sysv4.h
Hunk #1 succeeded at 566 (offset 15 lines).
Hunk #2 succeeded at 629 (offset 15 lines).
Hunk #3 succeeded at 808 (offset 15 lines).
Hunk #4 succeeded at 945 (offset 15 lines).
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1049k  100 1049k    0     0   742k      0  0:00:01  0:00:01 --:--:-- 1317k
tar: Error opening archive: Child process exited with status 254Child process exited with status 254

npm ERR! nodeos-cross-toolchain@0.0.0 preinstall: `scripts/preinstall`
npm ERR! Exit status 22
npm ERR! 
npm ERR! Failed at the nodeos-cross-toolchain@0.0.0 preinstall script.
npm ERR! This is most likely a problem with the nodeos-cross-toolchain package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/preinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeos-cross-toolchain
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/User/NodeOS/NodeOS
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/User/NodeOS/NodeOS/npm-debug.log
npm ERR! not ok code 0
```

The npm-debug.log contains

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
2 info using npm@1.4.28
3 info using node@v0.10.32
4 verbose readDependencies using package.json deps
5 verbose install where, deps [ '/Users/User/NodeOS/NodeOS', [] ]
6 info preinstall NodeOS@0.0.0
7 warn package.json nodeos-barebones@0.0.0 No repository field.
8 warn package.json nodeos-rootfs@0.0.0 No repository field.
9 warn package.json nodeos-initramfs@0.0.0 No repository field.
10 warn package.json nodeos-usersfs@0.0.0 No repository field.
11 verbose readDependencies using package.json deps
12 silly resolved []
13 info build /Users/User/NodeOS/NodeOS
14 verbose linkStuff [ false, false, false, '/Users/User/NodeOS' ]
15 info linkStuff NodeOS@0.0.0
16 verbose linkBins NodeOS@0.0.0
17 verbose linkMans NodeOS@0.0.0
18 verbose rebuildBundles NodeOS@0.0.0
19 verbose rebuildBundles [ 'nodeos-barebones',
19 verbose rebuildBundles   'nodeos-initramfs',
19 verbose rebuildBundles   'nodeos-rootfs',
19 verbose rebuildBundles   'nodeos-usersfs' ]
20 verbose rebuild bundle /Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones
21 info build /Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones
22 info preinstall nodeos-barebones@0.0.0
23 verbose unsafe-perm in lifecycle false
24 verbose linkStuff [ false,
24 verbose linkStuff   false,
24 verbose linkStuff   false,
24 verbose linkStuff   '/Users/User/NodeOS/NodeOS/node_modules' ]
25 info linkStuff nodeos-barebones@0.0.0
26 verbose linkBins nodeos-barebones@0.0.0
27 verbose linkMans nodeos-barebones@0.0.0
28 verbose rebuildBundles nodeos-barebones@0.0.0
29 verbose rebuildBundles [ '.gitignore', 'nodeos-cross-toolchain' ]
30 verbose rebuild bundle /Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain
31 info build /Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain
32 info preinstall nodeos-cross-toolchain@0.0.0
33 verbose unsafe-perm in lifecycle false
34 info nodeos-cross-toolchain@0.0.0 Failed to exec preinstall script
35 error nodeos-cross-toolchain@0.0.0 preinstall: `scripts/preinstall`
35 error Exit status 22
36 error Failed at the nodeos-cross-toolchain@0.0.0 preinstall script.
36 error This is most likely a problem with the nodeos-cross-toolchain package,
36 error not with npm itself.
36 error Tell the author that this fails on your system:
36 error     scripts/preinstall
36 error You can get their info via:
36 error     npm owner ls nodeos-cross-toolchain
36 error There is likely additional logging output above.
37 error System Darwin 11.4.2
38 error command "node" "/usr/local/bin/npm" "install"
39 error cwd /Users/User/NodeOS/NodeOS
40 error node -v v0.10.32
41 error npm -v 1.4.28
42 error code ELIFECYCLE
43 verbose exit [ 1, true ]
```

**Comment by piranna** [comment]
Your error seems related to [extracting the GCC libraries](https://github.com/NodeOS/NodeOS/blob/283a3035955a6c46d5dfc0686c34ac049296f8af/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/scripts/preinstall#L54). Seems you are using MacOS X, I have only tested to compile NodeOS from Linux, so maybe it's an issue regarding to the ```.tar.xz``` downloads and the OSX version of ```tar``` command not being capable to decompress it. Could you be able to change [this lines](https://github.com/NodeOS/NodeOS/blob/283a3035955a6c46d5dfc0686c34ac049296f8af/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/scripts/preinstall#L51-L52) and the other references to ```.tar.xz``` for ```.tar.gz```? I'm using XZ format when available since compress better than GZ and also it's the new GNU standard, but if it gives problems to compile on OSX, we can move them to use only GZ downloads :-)

**Comment by zodern** [comment]
Thank you.  I am on MacOS 10.7.5.  I made the changes and am running npm install again.

**Comment by piranna** [comment]
MacOS X only has support for ```.tar.xz``` files [starting on MacOS X 10.10 Yosemite](https://www.aeyoun.com/posts/archive-utility-xz.html). You'll have to upgrade or install the [xz tools](http://tukaani.org/xz/) yourself.

**Comment by piranna** [comment]
Or as I told before and you've done, make the changes on the scripts... :-)

**Comment by zodern** [comment]
I changed the lines to 
```
    mkdir -p mpfr && curl -L http://ftpmirror.gnu.org/mpfr/mpfr-3.1.2.tar.gz | tar xJf - -C mpfr --strip-components=1 &&
    mkdir -p gmp  && curl -L http://ftpmirror.gnu.org/gmp/gmp-6.0.0a.tar.gz  | tar xJf - -C gmp  --strip-components=1 &&
```

It ened sooner:

```
$ sudo npm install
npm WARN package.json nodeos-barebones@0.0.0 No repository field.
npm WARN package.json nodeos-usersfs@0.0.0 No repository field.
npm WARN package.json nodeos-initramfs@0.0.0 No repository field.
npm WARN package.json nodeos-rootfs@0.0.0 No repository field.

> nodeos-barebones@0.0.0 preinstall /Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones
> scripts/preinstall


> nodeos-cross-toolchain@0.0.0 preinstall /Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain
> scripts/preinstall

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 77.1M  100 77.1M    0     0   390k      0  0:03:22  0:03:22 --:--:--  698k
tar: Error opening archive: Child process exited with status 254Child process exited with status 254
```

I am downloading the xz tools.  I am using a Mac Book 2010 that has 2 gb of ram.  It doesn't have enough ram to upgrade :(.

**Comment by zodern** [comment]
I installed the tools and got this:
```
$ sudo npm install
npm WARN package.json nodeos-barebones@0.0.0 No repository field.
npm WARN package.json nodeos-initramfs@0.0.0 No repository field.
npm WARN package.json nodeos-usersfs@0.0.0 No repository field.
npm WARN package.json nodeos-rootfs@0.0.0 No repository field.

> nodeos-barebones@0.0.0 preinstall /Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones
> scripts/preinstall


> nodeos-cross-toolchain@0.0.0 preinstall /Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain
> scripts/preinstall

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  814k  100  814k    0     0   120k      0  0:00:06  0:00:06 --:--:--  157k

> nodeos-cross-toolchain@0.0.0 install /Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain
> scripts/install

/Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out/x86_64-nodeos-linux-musl/usr -> .
/Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out/x86_64-nodeos-linux-musl/lib64 -> lib
\e[37mExtracting Linux headers\e[0m
make: *** No rule to make target `mrproper'.  Stop.

```

**Comment by piranna** [comment]
> I changed the lines to
>
>     mkdir -p mpfr && curl -L http://ftpmirror.gnu.org/mpfr/mpfr-3.1.2.tar.gz | tar xJf - -C mpfr --strip-components=1 &&
>     mkdir -p gmp  && curl -L http://ftpmirror.gnu.org/gmp/gmp-6.0.0a.tar.gz  | tar xJf - -C gmp  --strip-components=1 &&

You need to change the de-compress flags from xJf to xzf, too ;-)


> It ended sooner:

That's normal, the scripts check what things are downloaded or
compiled to don't do it again ;-)


> I am downloading the xz tools. I am using a Mac Book 2010 that has 2 gb of ram. It doesn't have enough ram to upgrade :(.

Don't worry, probably by using the .tar.gz files is just enough :-)
Try again ;-)


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by zodern** [comment]
> I installed the tools and got this:

I forgot to mention I changed it back to xz after I installed the tools.

> You need to change the de-compress flags from xJf to xzf, too ;-)

I was wondering about that. I will try it.

**Comment by piranna** [comment]
> I installed the tools and got this:
>
>
> > nodeos-cross-toolchain@0.0.0 install /Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain
> > scripts/install
>
> /Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out/x86_64-nodeos-linux-musl/usr -> .
> /Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out/x86_64-nodeos-linux-musl/lib64 -> lib
> \e[37mExtracting Linux headers\e[0m
> make: *** No rule to make target `mrproper'.  Stop.

Strange error... good things are that files got to be downloaded :-)
But I would remove them and start again just to be sure. Remove all
the folders deps/, obj/ and out/ that you find on the node_modules.


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by zodern** [comment]
Now I am getting a different error: 

```
npm WARN package.json nodeos-rootfs@0.0.0 No repository field.
npm WARN package.json nodeos-barebones@0.0.0 No repository field.
npm WARN package.json nodeos-initramfs@0.0.0 No repository field.
npm WARN package.json nodeos-usersfs@0.0.0 No repository field.

> nodeos-barebones@0.0.0 preinstall /Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones
> scripts/preinstall

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16.4M  100 16.4M    0     0  1296k      0  0:00:12  0:00:12 --:--:-- 1053k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1247  100  1247    0     0   1983      0 --:--:-- --:--:-- --:--:--  5469
patching file ui_openssl.c

> nodeos-cross-toolchain@0.0.0 preinstall /Users/User/NodeOS/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain
> scripts/preinstall

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29.3M  100 29.3M    0     0   621k      0  0:00:48  0:00:48 --:--:--  627k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  101M  100  101M    0     0  1163k      0  0:01:29  0:01:29 --:--:-- 1374k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26649  100 26649    0     0  71334      0 --:--:-- --:--:-- --:--:--   98k
patching file libstdc++-v3/configure.host
Hunk #1 succeeded at 243 (offset -21 lines).
Hunk #2 succeeded at 258 (offset -21 lines).
patching file gcc/config.gcc
patching file gcc/config/linux.h
patching file gcc/config/linux.opt
patching file gcc/ginclude/stddef.h
patching file libgomp/config/posix/time.c
patching file libgcc/unwind-dw2-fde-dip.c
patching file gcc/configure
Hunk #1 succeeded at 26787 (offset 51 lines).
Hunk #2 succeeded at 26823 (offset 51 lines).
Hunk #3 succeeded at 26906 (offset 51 lines).
patching file gcc/configure.ac
Hunk #1 succeeded at 4664 (offset -55 lines).
Hunk #2 succeeded at 4700 (offset -55 lines).
Hunk #3 succeeded at 4766 (offset -55 lines).
patching file fixincludes/mkfixinc.sh
Hunk #1 succeeded at 20 (offset 1 line).
patching file config.sub
patching file gcc/config/i386/linux.h
Hunk #1 succeeded at 22 (offset 1 line).
patching file gcc/config/i386/linux64.h
Hunk #1 succeeded at 31 (offset 1 line).
patching file libitm/config/linux/x86/tls.h
patching file gcc/config/arm/linux-eabi.h
patching file libitm/config/arm/hwcap.cc
patching file gcc/config/mips/linux.h
Hunk #1 succeeded at 19 (offset 1 line).
patching file gcc/config.gcc
Hunk #1 succeeded at 2095 (offset -17 lines).
patching file gcc/config/rs6000/linux64.h
Hunk #1 succeeded at 362 (offset -2 lines).
patching file gcc/config/rs6000/secureplt.h
patching file gcc/config/rs6000/sysv4.h
Hunk #1 succeeded at 566 (offset 15 lines).
Hunk #2 succeeded at 629 (offset 15 lines).
Hunk #3 succeeded at 808 (offset 15 lines).
Hunk #4 succeeded at 945 (offset 15 lines).
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1583k  100 1583k    0     0   785k      0  0:00:02  0:00:02 --:--:-- 1064k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   286  100   286    0     0    712      0 --:--:-- --:--:-- --:--:--     0
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

Those lines are:
``` 
 mkdir -p mpfr && curl -L http://ftpmirror.gnu.org/mpfr/mpfr-3.1.2.tar.gz | tar xzf - -C mpfr --strip-components=1 &&
 mkdir -p gmp  && curl -L http://ftpmirror.gnu.org/gmp/gmp-6.0.0a.tar.gz | tar xzf - -C gmp  --strip-components=1 &&
```

**Comment by zodern** [comment]
I ran those commands in the terminal, and it is the second one that is making the error.  If I go to `http://mirror.team-cymru.org/gnu/gmp/gmp-6.0.0a.tar.gz` it shows 404 not found.  `http://mirror.team-cymru.org/gnu/gmp/` doesn't list any for that version in .tar.gz.

**Comment by piranna** [comment]
> I ran those commands in the terminal, and it is the second one that is making the error. If I go to http://mirror.team-cymru.org/gnu/gmp/gmp-6.0.0a.tar.gz it shows 404 not found. http://mirror.team-cymru.org/gnu/gmp/ doesn't list any for that version in .tar.gz.

What a shame... :-( Then we have here three options:

* Find another place that has a .tar.gz package
* Install the XZ tools
* Use an older version of the library like
http://mirror.team-cymru.org/gnu/gmp/gmp-5.1.3.tar.gz

Take your choice :-)


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by zodern** [comment]
I have XZ tools installed now so I removed NodeOS and cloned it again.  Running npm install outputed [this](https://gist.github.com/zodern/2bdf097d16b1a8013b8f).  It seemed there was at least one error per line in arch/x86/tools/relocs.c.

I am going to talk to the school and try to get permission to install linux in a vm on the laptop.

Thank you for your help.

**Comment by piranna** [comment]
That errors are about generating the Linux headers, so maybe it's not possible to do it on OSX. I'm honestly surprised about this since Linux kernel is self-contained, take a look about how to do it because it should be feasable.

**Comment by zodern** [comment]
After reading http://stackoverflow.com/questions/10018764/building-linux-kernel-on-mac-os-x I think I just need to get a Linux vm.

**Comment by piranna** [comment]
It's sad to see how difficult it is :-( Well, we'll need to add a comment
on the docs about a linux host is mandatory... :-/

2015-01-20 22:52 GMT+01:00 zodern <notifications@github.com>:

> After reading
> http://stackoverflow.com/questions/10018764/building-linux-kernel-on-mac-os-x
> I think I just need to get a Linux vm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NodeOS/NodeOS/issues/91#issuecomment-70741642>.
>



-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by aulvi** [comment]
Downsides of running a closed source OS to do open source work.

**Comment by piranna** [comment]
> Downsides of running a closed source OS to do open source work.

In fact, I see it an error of Linux kernel developers... according to the
StackOverflow link, why they are relying on external headers? Linux should
be self-contained.

**Comment by piranna** [comment]
@zodern, any updates on this?

**Comment by zodern** [comment]
I have a linux vm now.  I need to install nodejs and then I will try building NodeOS.  I plan to work on it later today.

**Comment by piranna** [comment]
:+1: Ok, tell me any progress you get :-)

**Comment by zodern** [comment]
It had gotten close.  The last part of the output is [here](https://gist.github.com/zodern/f1ed2bfe805c8d5f09de).  The terminal didn't keep anything before that.

**Comment by piranna** [comment]
> scripts/install: line 93: genext2fs: command not found

You need to ```genext2fs```, that's needed to generate the rootfs & usersfs disk image partitions. Good thing is, you've been able to compile NodeOS barebones and initramfs! :-) If you exec

```bash
cd node_modules/nodeos-barebones
npm start
```

you should get a Node.js REPL :-) You'll need to have installed the ```qemu-system-x86``` package to tun it.

**Comment by zodern** [comment]
It built sucessfully.  I installed qemu-system-x86, genext2fs and kvm.  When I try running it from the main folder or node_modules/nodeos-barebones I get this:

```
Test:~/NodeOS$ sudo npm start

> NodeOS@0.0.0 start /home/caiah/NodeOS
> scripts/start

Could not access KVM kernel module: No such file or directory
failed to initialize KVM: No such file or directory
```

**Comment by zodern** [comment]
Virtual box doesn't support kvm: https://www.virtualbox.org/ticket/4032

**Comment by piranna** [comment]
Comment the line with the ```--enable-kvm``` on ```scripts/start``` and try again, it will be fairly slower but should work.

**Comment by zodern** [comment]
It started!
Is the default username and password nodeos?
```
Welcome to NodeOS!: username:  
error:   Invalid input for username
Welcome to NodeOS!: username:  silk
User silk not found
error:   Invalid input for username
Welcome to NodeOS!: username:  nodeos
Welcome to NodeOS!: password:  
child_process.js:1147
    throw errnoException(err, 'spawn');
          ^
Error: spawn ENOMEM
    at exports._errnoException (util.js:742:11)
    at ChildProcess.spawn (child_process.js:1147:11)
    at exports.spawn (child_process.js:980:9)
    at /root/lib/node_modules/logon/index.js:138:3
    at /root/lib/node_modules/logon/node_modules/prompt/lib/prompt.js:316:32
    at /root/lib/node_modules/logon/node_modules/prompt/node_modules/utile/node_modules/async/lib/async.js:142:25
    at assembler (/root/lib/node_modules/logon/node_modules/prompt/lib/prompt.js:313:9)
    at /root/lib/node_modules/logon/node_modules/prompt/lib/prompt.js:322:32
    at /root/lib/node_modules/logon/node_modules/prompt/lib/prompt.js:597:5
    at Interface.onLine (/root/lib/node_modules/logon/node_modules/prompt/node_modules/read/lib/read.js:111:5)

Welcome to NodeOS!: username:  nodeos
Welcome to NodeOS!: password:  
child_process.js:1147
    throw errnoException(err, 'spawn');
          ^
Error: spawn ENOMEM
    at exports._errnoException (util.js:742:11)
    at ChildProcess.spawn (child_process.js:1147:11)
    at exports.spawn (child_process.js:980:9)
    at /root/lib/node_modules/logon/index.js:138:3
    at /root/lib/node_modules/logon/node_modules/prompt/lib/prompt.js:316:32
    at /root/lib/node_modules/logon/node_modules/prompt/node_modules/utile/node_modules/async/lib/async.js:142:25
    at assembler (/root/lib/node_modules/logon/node_modules/prompt/lib/prompt.js:313:9)
    at /root/lib/node_modules/logon/node_modules/prompt/lib/prompt.js:322:32
    at /root/lib/node_modules/logon/node_modules/prompt/lib/prompt.js:597:5
    at Interface.onLine (/root/lib/node_modules/logon/node_modules/prompt/node_modules/read/lib/read.js:111:5)
```

**Comment by piranna** [comment]
Congrats! Yes, it's nodeos:nodeos :-) Don't know why you are getting that
error, we'll need to test it thoroughly, but yes, you got it working :-D

Clossing the issue? ;-)

**Comment by zodern** [comment]
The issue can be closed.  Thank you for your help.

I will try to figure out what is causing the error.

**Comment by piranna** [comment]
You are welcome :-) If you need help with the error please open a new issue
:-)

2015-01-28 22:16 GMT+01:00 zodern <notifications@github.com>:

> The issue can be closed. Thank you for your help.
>
> I will try to figure out what is causing the error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NodeOS/NodeOS/issues/91#issuecomment-71917697>.
>



-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux
